# coding: utf-8
require 'test_helper'

class GdiplusLangIdTest < Test::Unit::TestCase
  include Gdiplus
  
  def test_langid
    assert_equal(0x0036, LangId.af.to_i)
    assert_equal(LangId.af, LangId.new("af"))
    assert_not_nil(LangId.new("AF").inspect.index("af"))
    assert_not_nil(LangId.new(0x0036).inspect.index("Afrikaans"))
    assert_equal(0x0436, LangId.af_ZA.to_i)
    assert_equal(LangId.af_ZA, LangId.new("af-ZA"))
    assert_not_nil(LangId.new("AF-ZA").inspect.index("af-ZA"))
    assert_not_nil(LangId.new(0x0436).inspect.index("Afrikaans (South Africa)"))
    assert_equal(0x005e, LangId.am.to_i)
    assert_equal(LangId.am, LangId.new("am"))
    assert_not_nil(LangId.new("AM").inspect.index("am"))
    assert_not_nil(LangId.new(0x005e).inspect.index("Amharic"))
    assert_equal(0x045e, LangId.am_ET.to_i)
    assert_equal(LangId.am_ET, LangId.new("am-ET"))
    assert_not_nil(LangId.new("AM-ET").inspect.index("am-ET"))
    assert_not_nil(LangId.new(0x045e).inspect.index("Amharic (Ethiopia)"))
    assert_equal(0x0001, LangId.ar.to_i)
    assert_equal(LangId.ar, LangId.new("ar"))
    assert_not_nil(LangId.new("AR").inspect.index("ar"))
    assert_not_nil(LangId.new(0x0001).inspect.index("Arabic"))
    assert_equal(0x3801, LangId.ar_AE.to_i)
    assert_equal(LangId.ar_AE, LangId.new("ar-AE"))
    assert_not_nil(LangId.new("AR-AE").inspect.index("ar-AE"))
    assert_not_nil(LangId.new(0x3801).inspect.index("Arabic (U.A.E.)"))
    assert_equal(0x3c01, LangId.ar_BH.to_i)
    assert_equal(LangId.ar_BH, LangId.new("ar-BH"))
    assert_not_nil(LangId.new("AR-BH").inspect.index("ar-BH"))
    assert_not_nil(LangId.new(0x3c01).inspect.index("Arabic (Bahrain)"))
    assert_equal(0x1401, LangId.ar_DZ.to_i)
    assert_equal(LangId.ar_DZ, LangId.new("ar-DZ"))
    assert_not_nil(LangId.new("AR-DZ").inspect.index("ar-DZ"))
    assert_not_nil(LangId.new(0x1401).inspect.index("Arabic (Algeria)"))
    assert_equal(0x0c01, LangId.ar_EG.to_i)
    assert_equal(LangId.ar_EG, LangId.new("ar-EG"))
    assert_not_nil(LangId.new("AR-EG").inspect.index("ar-EG"))
    assert_not_nil(LangId.new(0x0c01).inspect.index("Arabic (Egypt)"))
    assert_equal(0x0801, LangId.ar_IQ.to_i)
    assert_equal(LangId.ar_IQ, LangId.new("ar-IQ"))
    assert_not_nil(LangId.new("AR-IQ").inspect.index("ar-IQ"))
    assert_not_nil(LangId.new(0x0801).inspect.index("Arabic (Iraq)"))
    assert_equal(0x2c01, LangId.ar_JO.to_i)
    assert_equal(LangId.ar_JO, LangId.new("ar-JO"))
    assert_not_nil(LangId.new("AR-JO").inspect.index("ar-JO"))
    assert_not_nil(LangId.new(0x2c01).inspect.index("Arabic (Jordan)"))
    assert_equal(0x3401, LangId.ar_KW.to_i)
    assert_equal(LangId.ar_KW, LangId.new("ar-KW"))
    assert_not_nil(LangId.new("AR-KW").inspect.index("ar-KW"))
    assert_not_nil(LangId.new(0x3401).inspect.index("Arabic (Kuwait)"))
    assert_equal(0x3001, LangId.ar_LB.to_i)
    assert_equal(LangId.ar_LB, LangId.new("ar-LB"))
    assert_not_nil(LangId.new("AR-LB").inspect.index("ar-LB"))
    assert_not_nil(LangId.new(0x3001).inspect.index("Arabic (Lebanon)"))
    assert_equal(0x1001, LangId.ar_LY.to_i)
    assert_equal(LangId.ar_LY, LangId.new("ar-LY"))
    assert_not_nil(LangId.new("AR-LY").inspect.index("ar-LY"))
    assert_not_nil(LangId.new(0x1001).inspect.index("Arabic (Libya)"))
    assert_equal(0x1801, LangId.ar_MA.to_i)
    assert_equal(LangId.ar_MA, LangId.new("ar-MA"))
    assert_not_nil(LangId.new("AR-MA").inspect.index("ar-MA"))
    assert_not_nil(LangId.new(0x1801).inspect.index("Arabic (Morocco)"))
    assert_equal(0x2001, LangId.ar_OM.to_i)
    assert_equal(LangId.ar_OM, LangId.new("ar-OM"))
    assert_not_nil(LangId.new("AR-OM").inspect.index("ar-OM"))
    assert_not_nil(LangId.new(0x2001).inspect.index("Arabic (Oman)"))
    assert_equal(0x4001, LangId.ar_QA.to_i)
    assert_equal(LangId.ar_QA, LangId.new("ar-QA"))
    assert_not_nil(LangId.new("AR-QA").inspect.index("ar-QA"))
    assert_not_nil(LangId.new(0x4001).inspect.index("Arabic (Qatar)"))
    assert_equal(0x0401, LangId.ar_SA.to_i)
    assert_equal(LangId.ar_SA, LangId.new("ar-SA"))
    assert_not_nil(LangId.new("AR-SA").inspect.index("ar-SA"))
    assert_not_nil(LangId.new(0x0401).inspect.index("Arabic (Saudi Arabia)"))
    assert_equal(0x2801, LangId.ar_SY.to_i)
    assert_equal(LangId.ar_SY, LangId.new("ar-SY"))
    assert_not_nil(LangId.new("AR-SY").inspect.index("ar-SY"))
    assert_not_nil(LangId.new(0x2801).inspect.index("Arabic (Syria)"))
    assert_equal(0x1c01, LangId.ar_TN.to_i)
    assert_equal(LangId.ar_TN, LangId.new("ar-TN"))
    assert_not_nil(LangId.new("AR-TN").inspect.index("ar-TN"))
    assert_not_nil(LangId.new(0x1c01).inspect.index("Arabic (Tunisia)"))
    assert_equal(0x2401, LangId.ar_YE.to_i)
    assert_equal(LangId.ar_YE, LangId.new("ar-YE"))
    assert_not_nil(LangId.new("AR-YE").inspect.index("ar-YE"))
    assert_not_nil(LangId.new(0x2401).inspect.index("Arabic (Yemen)"))
    assert_equal(0x007a, LangId.arn.to_i)
    assert_equal(LangId.arn, LangId.new("arn"))
    assert_not_nil(LangId.new("ARN").inspect.index("arn"))
    assert_not_nil(LangId.new(0x007a).inspect.index("Mapudungun"))
    assert_equal(0x047a, LangId.arn_CL.to_i)
    assert_equal(LangId.arn_CL, LangId.new("arn-CL"))
    assert_not_nil(LangId.new("ARN-CL").inspect.index("arn-CL"))
    assert_not_nil(LangId.new(0x047a).inspect.index("Mapudungun (Chile)"))
    assert_equal(0x004d, LangId.as.to_i)
    assert_equal(LangId.as, LangId.new("as"))
    assert_not_nil(LangId.new("AS").inspect.index("as"))
    assert_not_nil(LangId.new(0x004d).inspect.index("Assamese"))
    assert_equal(0x044d, LangId.as_IN.to_i)
    assert_equal(LangId.as_IN, LangId.new("as-IN"))
    assert_not_nil(LangId.new("AS-IN").inspect.index("as-IN"))
    assert_not_nil(LangId.new(0x044d).inspect.index("Assamese (India)"))
    assert_equal(0x002c, LangId.az.to_i)
    assert_equal(LangId.az, LangId.new("az"))
    assert_not_nil(LangId.new("AZ").inspect.index("az"))
    assert_not_nil(LangId.new(0x002c).inspect.index("Azeri"))
    assert_equal(0x742c, LangId.az_Cyrl.to_i)
    assert_equal(LangId.az_Cyrl, LangId.new("az-Cyrl"))
    assert_not_nil(LangId.new("AZ-CYRL").inspect.index("az-Cyrl"))
    assert_not_nil(LangId.new(0x742c).inspect.index("Azeri (Cyrillic)"))
    assert_equal(0x082c, LangId.az_Cyrl_AZ.to_i)
    assert_equal(LangId.az_Cyrl_AZ, LangId.new("az-Cyrl-AZ"))
    assert_not_nil(LangId.new("AZ-CYRL-AZ").inspect.index("az-Cyrl-AZ"))
    assert_not_nil(LangId.new(0x082c).inspect.index("Azeri (Cyrillic, Azerbaijan)"))
    assert_equal(0x782c, LangId.az_Latn.to_i)
    assert_equal(LangId.az_Latn, LangId.new("az-Latn"))
    assert_not_nil(LangId.new("AZ-LATN").inspect.index("az-Latn"))
    assert_not_nil(LangId.new(0x782c).inspect.index("Azeri (Latin)"))
    assert_equal(0x042c, LangId.az_Latn_AZ.to_i)
    assert_equal(LangId.az_Latn_AZ, LangId.new("az-Latn-AZ"))
    assert_not_nil(LangId.new("AZ-LATN-AZ").inspect.index("az-Latn-AZ"))
    assert_not_nil(LangId.new(0x042c).inspect.index("Azeri (Latin, Azerbaijan)"))
    assert_equal(0x006d, LangId.ba.to_i)
    assert_equal(LangId.ba, LangId.new("ba"))
    assert_not_nil(LangId.new("BA").inspect.index("ba"))
    assert_not_nil(LangId.new(0x006d).inspect.index("Bashkir"))
    assert_equal(0x046d, LangId.ba_RU.to_i)
    assert_equal(LangId.ba_RU, LangId.new("ba-RU"))
    assert_not_nil(LangId.new("BA-RU").inspect.index("ba-RU"))
    assert_not_nil(LangId.new(0x046d).inspect.index("Bashkir (Russia)"))
    assert_equal(0x0023, LangId.be.to_i)
    assert_equal(LangId.be, LangId.new("be"))
    assert_not_nil(LangId.new("BE").inspect.index("be"))
    assert_not_nil(LangId.new(0x0023).inspect.index("Belarusian"))
    assert_equal(0x0423, LangId.be_BY.to_i)
    assert_equal(LangId.be_BY, LangId.new("be-BY"))
    assert_not_nil(LangId.new("BE-BY").inspect.index("be-BY"))
    assert_not_nil(LangId.new(0x0423).inspect.index("Belarusian (Belarus)"))
    assert_equal(0x0002, LangId.bg.to_i)
    assert_equal(LangId.bg, LangId.new("bg"))
    assert_not_nil(LangId.new("BG").inspect.index("bg"))
    assert_not_nil(LangId.new(0x0002).inspect.index("Bulgarian"))
    assert_equal(0x0402, LangId.bg_BG.to_i)
    assert_equal(LangId.bg_BG, LangId.new("bg-BG"))
    assert_not_nil(LangId.new("BG-BG").inspect.index("bg-BG"))
    assert_not_nil(LangId.new(0x0402).inspect.index("Bulgarian (Bulgaria)"))
    assert_equal(0x0045, LangId.bn.to_i)
    assert_equal(LangId.bn, LangId.new("bn"))
    assert_not_nil(LangId.new("BN").inspect.index("bn"))
    assert_not_nil(LangId.new(0x0045).inspect.index("Bengali"))
    assert_equal(0x0845, LangId.bn_BD.to_i)
    assert_equal(LangId.bn_BD, LangId.new("bn-BD"))
    assert_not_nil(LangId.new("BN-BD").inspect.index("bn-BD"))
    assert_not_nil(LangId.new(0x0845).inspect.index("Bengali (Bangladesh)"))
    assert_equal(0x0445, LangId.bn_IN.to_i)
    assert_equal(LangId.bn_IN, LangId.new("bn-IN"))
    assert_not_nil(LangId.new("BN-IN").inspect.index("bn-IN"))
    assert_not_nil(LangId.new(0x0445).inspect.index("Bengali (India)"))
    assert_equal(0x0051, LangId.bo.to_i)
    assert_equal(LangId.bo, LangId.new("bo"))
    assert_not_nil(LangId.new("BO").inspect.index("bo"))
    assert_not_nil(LangId.new(0x0051).inspect.index("Tibetan"))
    assert_equal(0x0451, LangId.bo_CN.to_i)
    assert_equal(LangId.bo_CN, LangId.new("bo-CN"))
    assert_not_nil(LangId.new("BO-CN").inspect.index("bo-CN"))
    assert_not_nil(LangId.new(0x0451).inspect.index("Tibetan (PRC)"))
    assert_equal(0x007e, LangId.br.to_i)
    assert_equal(LangId.br, LangId.new("br"))
    assert_not_nil(LangId.new("BR").inspect.index("br"))
    assert_not_nil(LangId.new(0x007e).inspect.index("Breton"))
    assert_equal(0x047e, LangId.br_FR.to_i)
    assert_equal(LangId.br_FR, LangId.new("br-FR"))
    assert_not_nil(LangId.new("BR-FR").inspect.index("br-FR"))
    assert_not_nil(LangId.new(0x047e).inspect.index("Breton (France)"))
    assert_equal(0x781a, LangId.bs.to_i)
    assert_equal(LangId.bs, LangId.new("bs"))
    assert_not_nil(LangId.new("BS").inspect.index("bs"))
    assert_not_nil(LangId.new(0x781a).inspect.index("Bosnian"))
    assert_equal(0x641a, LangId.bs_Cyrl.to_i)
    assert_equal(LangId.bs_Cyrl, LangId.new("bs-Cyrl"))
    assert_not_nil(LangId.new("BS-CYRL").inspect.index("bs-Cyrl"))
    assert_not_nil(LangId.new(0x641a).inspect.index("Bosnian (Cyrillic)"))
    assert_equal(0x201a, LangId.bs_Cyrl_BA.to_i)
    assert_equal(LangId.bs_Cyrl_BA, LangId.new("bs-Cyrl-BA"))
    assert_not_nil(LangId.new("BS-CYRL-BA").inspect.index("bs-Cyrl-BA"))
    assert_not_nil(LangId.new(0x201a).inspect.index("Bosnian (Cyrillic, Bosnia and Herzegovina)"))
    assert_equal(0x681a, LangId.bs_Latn.to_i)
    assert_equal(LangId.bs_Latn, LangId.new("bs-Latn"))
    assert_not_nil(LangId.new("BS-LATN").inspect.index("bs-Latn"))
    assert_not_nil(LangId.new(0x681a).inspect.index("Bosnian (Latin)"))
    assert_equal(0x141a, LangId.bs_Latn_BA.to_i)
    assert_equal(LangId.bs_Latn_BA, LangId.new("bs-Latn-BA"))
    assert_not_nil(LangId.new("BS-LATN-BA").inspect.index("bs-Latn-BA"))
    assert_not_nil(LangId.new(0x141a).inspect.index("Bosnian (Latin, Bosnia and Herzegovina)"))
    assert_equal(0x0003, LangId.ca.to_i)
    assert_equal(LangId.ca, LangId.new("ca"))
    assert_not_nil(LangId.new("CA").inspect.index("ca"))
    assert_not_nil(LangId.new(0x0003).inspect.index("Catalan"))
    assert_equal(0x0403, LangId.ca_ES.to_i)
    assert_equal(LangId.ca_ES, LangId.new("ca-ES"))
    assert_not_nil(LangId.new("CA-ES").inspect.index("ca-ES"))
    assert_not_nil(LangId.new(0x0403).inspect.index("Catalan (Catalan)"))
    assert_equal(0x0083, LangId.co.to_i)
    assert_equal(LangId.co, LangId.new("co"))
    assert_not_nil(LangId.new("CO").inspect.index("co"))
    assert_not_nil(LangId.new(0x0083).inspect.index("Corsican"))
    assert_equal(0x0483, LangId.co_FR.to_i)
    assert_equal(LangId.co_FR, LangId.new("co-FR"))
    assert_not_nil(LangId.new("CO-FR").inspect.index("co-FR"))
    assert_not_nil(LangId.new(0x0483).inspect.index("Corsican (France)"))
    assert_equal(0x0005, LangId.cs.to_i)
    assert_equal(LangId.cs, LangId.new("cs"))
    assert_not_nil(LangId.new("CS").inspect.index("cs"))
    assert_not_nil(LangId.new(0x0005).inspect.index("Czech"))
    assert_equal(0x0405, LangId.cs_CZ.to_i)
    assert_equal(LangId.cs_CZ, LangId.new("cs-CZ"))
    assert_not_nil(LangId.new("CS-CZ").inspect.index("cs-CZ"))
    assert_not_nil(LangId.new(0x0405).inspect.index("Czech (Czech Republic)"))
    assert_equal(0x0052, LangId.cy.to_i)
    assert_equal(LangId.cy, LangId.new("cy"))
    assert_not_nil(LangId.new("CY").inspect.index("cy"))
    assert_not_nil(LangId.new(0x0052).inspect.index("Welsh"))
    assert_equal(0x0452, LangId.cy_GB.to_i)
    assert_equal(LangId.cy_GB, LangId.new("cy-GB"))
    assert_not_nil(LangId.new("CY-GB").inspect.index("cy-GB"))
    assert_not_nil(LangId.new(0x0452).inspect.index("Welsh (United Kingdom)"))
    assert_equal(0x0006, LangId.da.to_i)
    assert_equal(LangId.da, LangId.new("da"))
    assert_not_nil(LangId.new("DA").inspect.index("da"))
    assert_not_nil(LangId.new(0x0006).inspect.index("Danish"))
    assert_equal(0x0406, LangId.da_DK.to_i)
    assert_equal(LangId.da_DK, LangId.new("da-DK"))
    assert_not_nil(LangId.new("DA-DK").inspect.index("da-DK"))
    assert_not_nil(LangId.new(0x0406).inspect.index("Danish (Denmark)"))
    assert_equal(0x0007, LangId.de.to_i)
    assert_equal(LangId.de, LangId.new("de"))
    assert_not_nil(LangId.new("DE").inspect.index("de"))
    assert_not_nil(LangId.new(0x0007).inspect.index("German"))
    assert_equal(0x0c07, LangId.de_AT.to_i)
    assert_equal(LangId.de_AT, LangId.new("de-AT"))
    assert_not_nil(LangId.new("DE-AT").inspect.index("de-AT"))
    assert_not_nil(LangId.new(0x0c07).inspect.index("German (Austria)"))
    assert_equal(0x0807, LangId.de_CH.to_i)
    assert_equal(LangId.de_CH, LangId.new("de-CH"))
    assert_not_nil(LangId.new("DE-CH").inspect.index("de-CH"))
    assert_not_nil(LangId.new(0x0807).inspect.index("German (Switzerland)"))
    assert_equal(0x0407, LangId.de_DE.to_i)
    assert_equal(LangId.de_DE, LangId.new("de-DE"))
    assert_not_nil(LangId.new("DE-DE").inspect.index("de-DE"))
    assert_not_nil(LangId.new(0x0407).inspect.index("German (Germany)"))
    assert_equal(0x1407, LangId.de_LI.to_i)
    assert_equal(LangId.de_LI, LangId.new("de-LI"))
    assert_not_nil(LangId.new("DE-LI").inspect.index("de-LI"))
    assert_not_nil(LangId.new(0x1407).inspect.index("German (Liechtenstein)"))
    assert_equal(0x1007, LangId.de_LU.to_i)
    assert_equal(LangId.de_LU, LangId.new("de-LU"))
    assert_not_nil(LangId.new("DE-LU").inspect.index("de-LU"))
    assert_not_nil(LangId.new(0x1007).inspect.index("German (Luxembourg)"))
    assert_equal(0x7c2e, LangId.dsb.to_i)
    assert_equal(LangId.dsb, LangId.new("dsb"))
    assert_not_nil(LangId.new("DSB").inspect.index("dsb"))
    assert_not_nil(LangId.new(0x7c2e).inspect.index("Lower Sorbian"))
    assert_equal(0x082e, LangId.dsb_DE.to_i)
    assert_equal(LangId.dsb_DE, LangId.new("dsb-DE"))
    assert_not_nil(LangId.new("DSB-DE").inspect.index("dsb-DE"))
    assert_not_nil(LangId.new(0x082e).inspect.index("Lower Sorbian (Germany)"))
    assert_equal(0x0065, LangId.dv.to_i)
    assert_equal(LangId.dv, LangId.new("dv"))
    assert_not_nil(LangId.new("DV").inspect.index("dv"))
    assert_not_nil(LangId.new(0x0065).inspect.index("Divehi"))
    assert_equal(0x0465, LangId.dv_MV.to_i)
    assert_equal(LangId.dv_MV, LangId.new("dv-MV"))
    assert_not_nil(LangId.new("DV-MV").inspect.index("dv-MV"))
    assert_not_nil(LangId.new(0x0465).inspect.index("Divehi (Maldives)"))
    assert_equal(0x0008, LangId.el.to_i)
    assert_equal(LangId.el, LangId.new("el"))
    assert_not_nil(LangId.new("EL").inspect.index("el"))
    assert_not_nil(LangId.new(0x0008).inspect.index("Greek"))
    assert_equal(0x0408, LangId.el_GR.to_i)
    assert_equal(LangId.el_GR, LangId.new("el-GR"))
    assert_not_nil(LangId.new("EL-GR").inspect.index("el-GR"))
    assert_not_nil(LangId.new(0x0408).inspect.index("Greek (Greece)"))
    assert_equal(0x0009, LangId.en.to_i)
    assert_equal(LangId.en, LangId.new("en"))
    assert_not_nil(LangId.new("EN").inspect.index("en"))
    assert_not_nil(LangId.new(0x0009).inspect.index("English"))
    assert_equal(0x2409, LangId.en_029.to_i)
    assert_equal(LangId.en_029, LangId.new("en-029"))
    assert_not_nil(LangId.new("EN-029").inspect.index("en-029"))
    assert_not_nil(LangId.new(0x2409).inspect.index("English (Caribbean)"))
    assert_equal(0x0c09, LangId.en_AU.to_i)
    assert_equal(LangId.en_AU, LangId.new("en-AU"))
    assert_not_nil(LangId.new("EN-AU").inspect.index("en-AU"))
    assert_not_nil(LangId.new(0x0c09).inspect.index("English (Australia)"))
    assert_equal(0x2809, LangId.en_BZ.to_i)
    assert_equal(LangId.en_BZ, LangId.new("en-BZ"))
    assert_not_nil(LangId.new("EN-BZ").inspect.index("en-BZ"))
    assert_not_nil(LangId.new(0x2809).inspect.index("English (Belize)"))
    assert_equal(0x1009, LangId.en_CA.to_i)
    assert_equal(LangId.en_CA, LangId.new("en-CA"))
    assert_not_nil(LangId.new("EN-CA").inspect.index("en-CA"))
    assert_not_nil(LangId.new(0x1009).inspect.index("English (Canada)"))
    assert_equal(0x0809, LangId.en_GB.to_i)
    assert_equal(LangId.en_GB, LangId.new("en-GB"))
    assert_not_nil(LangId.new("EN-GB").inspect.index("en-GB"))
    assert_not_nil(LangId.new(0x0809).inspect.index("English (United Kingdom)"))
    assert_equal(0x1809, LangId.en_IE.to_i)
    assert_equal(LangId.en_IE, LangId.new("en-IE"))
    assert_not_nil(LangId.new("EN-IE").inspect.index("en-IE"))
    assert_not_nil(LangId.new(0x1809).inspect.index("English (Ireland)"))
    assert_equal(0x4009, LangId.en_IN.to_i)
    assert_equal(LangId.en_IN, LangId.new("en-IN"))
    assert_not_nil(LangId.new("EN-IN").inspect.index("en-IN"))
    assert_not_nil(LangId.new(0x4009).inspect.index("English (India)"))
    assert_equal(0x2009, LangId.en_JM.to_i)
    assert_equal(LangId.en_JM, LangId.new("en-JM"))
    assert_not_nil(LangId.new("EN-JM").inspect.index("en-JM"))
    assert_not_nil(LangId.new(0x2009).inspect.index("English (Jamaica)"))
    assert_equal(0x4409, LangId.en_MY.to_i)
    assert_equal(LangId.en_MY, LangId.new("en-MY"))
    assert_not_nil(LangId.new("EN-MY").inspect.index("en-MY"))
    assert_not_nil(LangId.new(0x4409).inspect.index("English (Malaysia)"))
    assert_equal(0x1409, LangId.en_NZ.to_i)
    assert_equal(LangId.en_NZ, LangId.new("en-NZ"))
    assert_not_nil(LangId.new("EN-NZ").inspect.index("en-NZ"))
    assert_not_nil(LangId.new(0x1409).inspect.index("English (New Zealand)"))
    assert_equal(0x3409, LangId.en_PH.to_i)
    assert_equal(LangId.en_PH, LangId.new("en-PH"))
    assert_not_nil(LangId.new("EN-PH").inspect.index("en-PH"))
    assert_not_nil(LangId.new(0x3409).inspect.index("English (Republic of the Philippines)"))
    assert_equal(0x4809, LangId.en_SG.to_i)
    assert_equal(LangId.en_SG, LangId.new("en-SG"))
    assert_not_nil(LangId.new("EN-SG").inspect.index("en-SG"))
    assert_not_nil(LangId.new(0x4809).inspect.index("English (Singapore)"))
    assert_equal(0x2c09, LangId.en_TT.to_i)
    assert_equal(LangId.en_TT, LangId.new("en-TT"))
    assert_not_nil(LangId.new("EN-TT").inspect.index("en-TT"))
    assert_not_nil(LangId.new(0x2c09).inspect.index("English (Trinidad and Tobago)"))
    assert_equal(0x0409, LangId.en_US.to_i)
    assert_equal(LangId.en_US, LangId.new("en-US"))
    assert_not_nil(LangId.new("EN-US").inspect.index("en-US"))
    assert_not_nil(LangId.new(0x0409).inspect.index("English (United States)"))
    assert_equal(0x1c09, LangId.en_ZA.to_i)
    assert_equal(LangId.en_ZA, LangId.new("en-ZA"))
    assert_not_nil(LangId.new("EN-ZA").inspect.index("en-ZA"))
    assert_not_nil(LangId.new(0x1c09).inspect.index("English (South Africa)"))
    assert_equal(0x3009, LangId.en_ZW.to_i)
    assert_equal(LangId.en_ZW, LangId.new("en-ZW"))
    assert_not_nil(LangId.new("EN-ZW").inspect.index("en-ZW"))
    assert_not_nil(LangId.new(0x3009).inspect.index("English (Zimbabwe)"))
    assert_equal(0x000a, LangId.es.to_i)
    assert_equal(LangId.es, LangId.new("es"))
    assert_not_nil(LangId.new("ES").inspect.index("es"))
    assert_not_nil(LangId.new(0x000a).inspect.index("Spanish"))
    assert_equal(0x2c0a, LangId.es_AR.to_i)
    assert_equal(LangId.es_AR, LangId.new("es-AR"))
    assert_not_nil(LangId.new("ES-AR").inspect.index("es-AR"))
    assert_not_nil(LangId.new(0x2c0a).inspect.index("Spanish (Argentina)"))
    assert_equal(0x400a, LangId.es_BO.to_i)
    assert_equal(LangId.es_BO, LangId.new("es-BO"))
    assert_not_nil(LangId.new("ES-BO").inspect.index("es-BO"))
    assert_not_nil(LangId.new(0x400a).inspect.index("Spanish (Bolivia)"))
    assert_equal(0x340a, LangId.es_CL.to_i)
    assert_equal(LangId.es_CL, LangId.new("es-CL"))
    assert_not_nil(LangId.new("ES-CL").inspect.index("es-CL"))
    assert_not_nil(LangId.new(0x340a).inspect.index("Spanish (Chile)"))
    assert_equal(0x240a, LangId.es_CO.to_i)
    assert_equal(LangId.es_CO, LangId.new("es-CO"))
    assert_not_nil(LangId.new("ES-CO").inspect.index("es-CO"))
    assert_not_nil(LangId.new(0x240a).inspect.index("Spanish (Colombia)"))
    assert_equal(0x140a, LangId.es_CR.to_i)
    assert_equal(LangId.es_CR, LangId.new("es-CR"))
    assert_not_nil(LangId.new("ES-CR").inspect.index("es-CR"))
    assert_not_nil(LangId.new(0x140a).inspect.index("Spanish (Costa Rica)"))
    assert_equal(0x1c0a, LangId.es_DO.to_i)
    assert_equal(LangId.es_DO, LangId.new("es-DO"))
    assert_not_nil(LangId.new("ES-DO").inspect.index("es-DO"))
    assert_not_nil(LangId.new(0x1c0a).inspect.index("Spanish (Dominican Republic)"))
    assert_equal(0x300a, LangId.es_EC.to_i)
    assert_equal(LangId.es_EC, LangId.new("es-EC"))
    assert_not_nil(LangId.new("ES-EC").inspect.index("es-EC"))
    assert_not_nil(LangId.new(0x300a).inspect.index("Spanish (Ecuador)"))
    assert_equal(0x0c0a, LangId.es_ES.to_i)
    assert_equal(LangId.es_ES, LangId.new("es-ES"))
    assert_not_nil(LangId.new("ES-ES").inspect.index("es-ES"))
    assert_not_nil(LangId.new(0x0c0a).inspect.index("Spanish (Spain, International Sort)"))
    assert_equal(0x100a, LangId.es_GT.to_i)
    assert_equal(LangId.es_GT, LangId.new("es-GT"))
    assert_not_nil(LangId.new("ES-GT").inspect.index("es-GT"))
    assert_not_nil(LangId.new(0x100a).inspect.index("Spanish (Guatemala)"))
    assert_equal(0x480a, LangId.es_HN.to_i)
    assert_equal(LangId.es_HN, LangId.new("es-HN"))
    assert_not_nil(LangId.new("ES-HN").inspect.index("es-HN"))
    assert_not_nil(LangId.new(0x480a).inspect.index("Spanish (Honduras)"))
    assert_equal(0x080a, LangId.es_MX.to_i)
    assert_equal(LangId.es_MX, LangId.new("es-MX"))
    assert_not_nil(LangId.new("ES-MX").inspect.index("es-MX"))
    assert_not_nil(LangId.new(0x080a).inspect.index("Spanish (Mexico)"))
    assert_equal(0x4c0a, LangId.es_NI.to_i)
    assert_equal(LangId.es_NI, LangId.new("es-NI"))
    assert_not_nil(LangId.new("ES-NI").inspect.index("es-NI"))
    assert_not_nil(LangId.new(0x4c0a).inspect.index("Spanish (Nicaragua)"))
    assert_equal(0x180a, LangId.es_PA.to_i)
    assert_equal(LangId.es_PA, LangId.new("es-PA"))
    assert_not_nil(LangId.new("ES-PA").inspect.index("es-PA"))
    assert_not_nil(LangId.new(0x180a).inspect.index("Spanish (Panama)"))
    assert_equal(0x280a, LangId.es_PE.to_i)
    assert_equal(LangId.es_PE, LangId.new("es-PE"))
    assert_not_nil(LangId.new("ES-PE").inspect.index("es-PE"))
    assert_not_nil(LangId.new(0x280a).inspect.index("Spanish (Peru)"))
    assert_equal(0x500a, LangId.es_PR.to_i)
    assert_equal(LangId.es_PR, LangId.new("es-PR"))
    assert_not_nil(LangId.new("ES-PR").inspect.index("es-PR"))
    assert_not_nil(LangId.new(0x500a).inspect.index("Spanish (Puerto Rico)"))
    assert_equal(0x3c0a, LangId.es_PY.to_i)
    assert_equal(LangId.es_PY, LangId.new("es-PY"))
    assert_not_nil(LangId.new("ES-PY").inspect.index("es-PY"))
    assert_not_nil(LangId.new(0x3c0a).inspect.index("Spanish (Paraguay)"))
    assert_equal(0x440a, LangId.es_SV.to_i)
    assert_equal(LangId.es_SV, LangId.new("es-SV"))
    assert_not_nil(LangId.new("ES-SV").inspect.index("es-SV"))
    assert_not_nil(LangId.new(0x440a).inspect.index("Spanish (El Salvador)"))
    assert_equal(0x540a, LangId.es_US.to_i)
    assert_equal(LangId.es_US, LangId.new("es-US"))
    assert_not_nil(LangId.new("ES-US").inspect.index("es-US"))
    assert_not_nil(LangId.new(0x540a).inspect.index("Spanish (United States)"))
    assert_equal(0x380a, LangId.es_UY.to_i)
    assert_equal(LangId.es_UY, LangId.new("es-UY"))
    assert_not_nil(LangId.new("ES-UY").inspect.index("es-UY"))
    assert_not_nil(LangId.new(0x380a).inspect.index("Spanish (Uruguay)"))
    assert_equal(0x200a, LangId.es_VE.to_i)
    assert_equal(LangId.es_VE, LangId.new("es-VE"))
    assert_not_nil(LangId.new("ES-VE").inspect.index("es-VE"))
    assert_not_nil(LangId.new(0x200a).inspect.index("Spanish (Bolivarian Republic of Venezuela)"))
    assert_equal(0x0025, LangId.et.to_i)
    assert_equal(LangId.et, LangId.new("et"))
    assert_not_nil(LangId.new("ET").inspect.index("et"))
    assert_not_nil(LangId.new(0x0025).inspect.index("Estonian"))
    assert_equal(0x0425, LangId.et_EE.to_i)
    assert_equal(LangId.et_EE, LangId.new("et-EE"))
    assert_not_nil(LangId.new("ET-EE").inspect.index("et-EE"))
    assert_not_nil(LangId.new(0x0425).inspect.index("Estonian (Estonia)"))
    assert_equal(0x002d, LangId.eu.to_i)
    assert_equal(LangId.eu, LangId.new("eu"))
    assert_not_nil(LangId.new("EU").inspect.index("eu"))
    assert_not_nil(LangId.new(0x002d).inspect.index("Basque"))
    assert_equal(0x042d, LangId.eu_ES.to_i)
    assert_equal(LangId.eu_ES, LangId.new("eu-ES"))
    assert_not_nil(LangId.new("EU-ES").inspect.index("eu-ES"))
    assert_not_nil(LangId.new(0x042d).inspect.index("Basque (Basque)"))
    assert_equal(0x0029, LangId.fa.to_i)
    assert_equal(LangId.fa, LangId.new("fa"))
    assert_not_nil(LangId.new("FA").inspect.index("fa"))
    assert_not_nil(LangId.new(0x0029).inspect.index("Persian"))
    assert_equal(0x0429, LangId.fa_IR.to_i)
    assert_equal(LangId.fa_IR, LangId.new("fa-IR"))
    assert_not_nil(LangId.new("FA-IR").inspect.index("fa-IR"))
    assert_not_nil(LangId.new(0x0429).inspect.index("Persian"))
    assert_equal(0x000b, LangId.fi.to_i)
    assert_equal(LangId.fi, LangId.new("fi"))
    assert_not_nil(LangId.new("FI").inspect.index("fi"))
    assert_not_nil(LangId.new(0x000b).inspect.index("Finnish"))
    assert_equal(0x040b, LangId.fi_FI.to_i)
    assert_equal(LangId.fi_FI, LangId.new("fi-FI"))
    assert_not_nil(LangId.new("FI-FI").inspect.index("fi-FI"))
    assert_not_nil(LangId.new(0x040b).inspect.index("Finnish (Finland)"))
    assert_equal(0x0064, LangId.fil.to_i)
    assert_equal(LangId.fil, LangId.new("fil"))
    assert_not_nil(LangId.new("FIL").inspect.index("fil"))
    assert_not_nil(LangId.new(0x0064).inspect.index("Filipino"))
    assert_equal(0x0464, LangId.fil_PH.to_i)
    assert_equal(LangId.fil_PH, LangId.new("fil-PH"))
    assert_not_nil(LangId.new("FIL-PH").inspect.index("fil-PH"))
    assert_not_nil(LangId.new(0x0464).inspect.index("Filipino (Philippines)"))
    assert_equal(0x0038, LangId.fo.to_i)
    assert_equal(LangId.fo, LangId.new("fo"))
    assert_not_nil(LangId.new("FO").inspect.index("fo"))
    assert_not_nil(LangId.new(0x0038).inspect.index("Faroese"))
    assert_equal(0x0438, LangId.fo_FO.to_i)
    assert_equal(LangId.fo_FO, LangId.new("fo-FO"))
    assert_not_nil(LangId.new("FO-FO").inspect.index("fo-FO"))
    assert_not_nil(LangId.new(0x0438).inspect.index("Faroese (Faroe Islands)"))
    assert_equal(0x000c, LangId.fr.to_i)
    assert_equal(LangId.fr, LangId.new("fr"))
    assert_not_nil(LangId.new("FR").inspect.index("fr"))
    assert_not_nil(LangId.new(0x000c).inspect.index("French"))
    assert_equal(0x080c, LangId.fr_BE.to_i)
    assert_equal(LangId.fr_BE, LangId.new("fr-BE"))
    assert_not_nil(LangId.new("FR-BE").inspect.index("fr-BE"))
    assert_not_nil(LangId.new(0x080c).inspect.index("French (Belgium)"))
    assert_equal(0x0c0c, LangId.fr_CA.to_i)
    assert_equal(LangId.fr_CA, LangId.new("fr-CA"))
    assert_not_nil(LangId.new("FR-CA").inspect.index("fr-CA"))
    assert_not_nil(LangId.new(0x0c0c).inspect.index("French (Canada)"))
    assert_equal(0x100c, LangId.fr_CH.to_i)
    assert_equal(LangId.fr_CH, LangId.new("fr-CH"))
    assert_not_nil(LangId.new("FR-CH").inspect.index("fr-CH"))
    assert_not_nil(LangId.new(0x100c).inspect.index("French (Switzerland)"))
    assert_equal(0x040c, LangId.fr_FR.to_i)
    assert_equal(LangId.fr_FR, LangId.new("fr-FR"))
    assert_not_nil(LangId.new("FR-FR").inspect.index("fr-FR"))
    assert_not_nil(LangId.new(0x040c).inspect.index("French (France)"))
    assert_equal(0x140c, LangId.fr_LU.to_i)
    assert_equal(LangId.fr_LU, LangId.new("fr-LU"))
    assert_not_nil(LangId.new("FR-LU").inspect.index("fr-LU"))
    assert_not_nil(LangId.new(0x140c).inspect.index("French (Luxembourg)"))
    assert_equal(0x180c, LangId.fr_MC.to_i)
    assert_equal(LangId.fr_MC, LangId.new("fr-MC"))
    assert_not_nil(LangId.new("FR-MC").inspect.index("fr-MC"))
    assert_not_nil(LangId.new(0x180c).inspect.index("French (Monaco)"))
    assert_equal(0x0062, LangId.fy.to_i)
    assert_equal(LangId.fy, LangId.new("fy"))
    assert_not_nil(LangId.new("FY").inspect.index("fy"))
    assert_not_nil(LangId.new(0x0062).inspect.index("Frisian"))
    assert_equal(0x0462, LangId.fy_NL.to_i)
    assert_equal(LangId.fy_NL, LangId.new("fy-NL"))
    assert_not_nil(LangId.new("FY-NL").inspect.index("fy-NL"))
    assert_not_nil(LangId.new(0x0462).inspect.index("Frisian (Netherlands)"))
    assert_equal(0x003c, LangId.ga.to_i)
    assert_equal(LangId.ga, LangId.new("ga"))
    assert_not_nil(LangId.new("GA").inspect.index("ga"))
    assert_not_nil(LangId.new(0x003c).inspect.index("Irish"))
    assert_equal(0x083c, LangId.ga_IE.to_i)
    assert_equal(LangId.ga_IE, LangId.new("ga-IE"))
    assert_not_nil(LangId.new("GA-IE").inspect.index("ga-IE"))
    assert_not_nil(LangId.new(0x083c).inspect.index("Irish (Ireland)"))
    assert_equal(0x0091, LangId.gd.to_i)
    assert_equal(LangId.gd, LangId.new("gd"))
    assert_not_nil(LangId.new("GD").inspect.index("gd"))
    assert_not_nil(LangId.new(0x0091).inspect.index("Scottish Gaelic"))
    assert_equal(0x0491, LangId.gd_GB.to_i)
    assert_equal(LangId.gd_GB, LangId.new("gd-GB"))
    assert_not_nil(LangId.new("GD-GB").inspect.index("gd-GB"))
    assert_not_nil(LangId.new(0x0491).inspect.index("Scottish Gaelic (United Kingdom)"))
    assert_equal(0x0056, LangId.gl.to_i)
    assert_equal(LangId.gl, LangId.new("gl"))
    assert_not_nil(LangId.new("GL").inspect.index("gl"))
    assert_not_nil(LangId.new(0x0056).inspect.index("Galician"))
    assert_equal(0x0456, LangId.gl_ES.to_i)
    assert_equal(LangId.gl_ES, LangId.new("gl-ES"))
    assert_not_nil(LangId.new("GL-ES").inspect.index("gl-ES"))
    assert_not_nil(LangId.new(0x0456).inspect.index("Galician (Galician)"))
    assert_equal(0x0084, LangId.gsw.to_i)
    assert_equal(LangId.gsw, LangId.new("gsw"))
    assert_not_nil(LangId.new("GSW").inspect.index("gsw"))
    assert_not_nil(LangId.new(0x0084).inspect.index("Alsatian"))
    assert_equal(0x0484, LangId.gsw_FR.to_i)
    assert_equal(LangId.gsw_FR, LangId.new("gsw-FR"))
    assert_not_nil(LangId.new("GSW-FR").inspect.index("gsw-FR"))
    assert_not_nil(LangId.new(0x0484).inspect.index("Alsatian (France)"))
    assert_equal(0x0047, LangId.gu.to_i)
    assert_equal(LangId.gu, LangId.new("gu"))
    assert_not_nil(LangId.new("GU").inspect.index("gu"))
    assert_not_nil(LangId.new(0x0047).inspect.index("Gujarati"))
    assert_equal(0x0447, LangId.gu_IN.to_i)
    assert_equal(LangId.gu_IN, LangId.new("gu-IN"))
    assert_not_nil(LangId.new("GU-IN").inspect.index("gu-IN"))
    assert_not_nil(LangId.new(0x0447).inspect.index("Gujarati (India)"))
    assert_equal(0x0068, LangId.ha.to_i)
    assert_equal(LangId.ha, LangId.new("ha"))
    assert_not_nil(LangId.new("HA").inspect.index("ha"))
    assert_not_nil(LangId.new(0x0068).inspect.index("Hausa"))
    assert_equal(0x7c68, LangId.ha_Latn.to_i)
    assert_equal(LangId.ha_Latn, LangId.new("ha-Latn"))
    assert_not_nil(LangId.new("HA-LATN").inspect.index("ha-Latn"))
    assert_not_nil(LangId.new(0x7c68).inspect.index("Hausa (Latin)"))
    assert_equal(0x0468, LangId.ha_Latn_NG.to_i)
    assert_equal(LangId.ha_Latn_NG, LangId.new("ha-Latn-NG"))
    assert_not_nil(LangId.new("HA-LATN-NG").inspect.index("ha-Latn-NG"))
    assert_not_nil(LangId.new(0x0468).inspect.index("Hausa (Latin, Nigeria)"))
    assert_equal(0x000d, LangId.he.to_i)
    assert_equal(LangId.he, LangId.new("he"))
    assert_not_nil(LangId.new("HE").inspect.index("he"))
    assert_not_nil(LangId.new(0x000d).inspect.index("Hebrew"))
    assert_equal(0x040d, LangId.he_IL.to_i)
    assert_equal(LangId.he_IL, LangId.new("he-IL"))
    assert_not_nil(LangId.new("HE-IL").inspect.index("he-IL"))
    assert_not_nil(LangId.new(0x040d).inspect.index("Hebrew (Israel)"))
    assert_equal(0x0039, LangId.hi.to_i)
    assert_equal(LangId.hi, LangId.new("hi"))
    assert_not_nil(LangId.new("HI").inspect.index("hi"))
    assert_not_nil(LangId.new(0x0039).inspect.index("Hindi"))
    assert_equal(0x0439, LangId.hi_IN.to_i)
    assert_equal(LangId.hi_IN, LangId.new("hi-IN"))
    assert_not_nil(LangId.new("HI-IN").inspect.index("hi-IN"))
    assert_not_nil(LangId.new(0x0439).inspect.index("Hindi (India)"))
    assert_equal(0x001a, LangId.hr.to_i)
    assert_equal(LangId.hr, LangId.new("hr"))
    assert_not_nil(LangId.new("HR").inspect.index("hr"))
    assert_not_nil(LangId.new(0x001a).inspect.index("Croatian"))
    assert_equal(0x101a, LangId.hr_BA.to_i)
    assert_equal(LangId.hr_BA, LangId.new("hr-BA"))
    assert_not_nil(LangId.new("HR-BA").inspect.index("hr-BA"))
    assert_not_nil(LangId.new(0x101a).inspect.index("Croatian (Latin, Bosnia and Herzegovina)"))
    assert_equal(0x041a, LangId.hr_HR.to_i)
    assert_equal(LangId.hr_HR, LangId.new("hr-HR"))
    assert_not_nil(LangId.new("HR-HR").inspect.index("hr-HR"))
    assert_not_nil(LangId.new(0x041a).inspect.index("Croatian (Croatia)"))
    assert_equal(0x002e, LangId.hsb.to_i)
    assert_equal(LangId.hsb, LangId.new("hsb"))
    assert_not_nil(LangId.new("HSB").inspect.index("hsb"))
    assert_not_nil(LangId.new(0x002e).inspect.index("Upper Sorbian"))
    assert_equal(0x042e, LangId.hsb_DE.to_i)
    assert_equal(LangId.hsb_DE, LangId.new("hsb-DE"))
    assert_not_nil(LangId.new("HSB-DE").inspect.index("hsb-DE"))
    assert_not_nil(LangId.new(0x042e).inspect.index("Upper Sorbian (Germany)"))
    assert_equal(0x000e, LangId.hu.to_i)
    assert_equal(LangId.hu, LangId.new("hu"))
    assert_not_nil(LangId.new("HU").inspect.index("hu"))
    assert_not_nil(LangId.new(0x000e).inspect.index("Hungarian"))
    assert_equal(0x040e, LangId.hu_HU.to_i)
    assert_equal(LangId.hu_HU, LangId.new("hu-HU"))
    assert_not_nil(LangId.new("HU-HU").inspect.index("hu-HU"))
    assert_not_nil(LangId.new(0x040e).inspect.index("Hungarian (Hungary)"))
    assert_equal(0x002b, LangId.hy.to_i)
    assert_equal(LangId.hy, LangId.new("hy"))
    assert_not_nil(LangId.new("HY").inspect.index("hy"))
    assert_not_nil(LangId.new(0x002b).inspect.index("Armenian"))
    assert_equal(0x042b, LangId.hy_AM.to_i)
    assert_equal(LangId.hy_AM, LangId.new("hy-AM"))
    assert_not_nil(LangId.new("HY-AM").inspect.index("hy-AM"))
    assert_not_nil(LangId.new(0x042b).inspect.index("Armenian (Armenia)"))
    assert_equal(0x0021, LangId.id.to_i)
    assert_equal(LangId.id, LangId.new("id"))
    assert_not_nil(LangId.new("ID").inspect.index("id"))
    assert_not_nil(LangId.new(0x0021).inspect.index("Indonesian"))
    assert_equal(0x0421, LangId.id_ID.to_i)
    assert_equal(LangId.id_ID, LangId.new("id-ID"))
    assert_not_nil(LangId.new("ID-ID").inspect.index("id-ID"))
    assert_not_nil(LangId.new(0x0421).inspect.index("Indonesian (Indonesia)"))
    assert_equal(0x0070, LangId.ig.to_i)
    assert_equal(LangId.ig, LangId.new("ig"))
    assert_not_nil(LangId.new("IG").inspect.index("ig"))
    assert_not_nil(LangId.new(0x0070).inspect.index("Igbo"))
    assert_equal(0x0470, LangId.ig_NG.to_i)
    assert_equal(LangId.ig_NG, LangId.new("ig-NG"))
    assert_not_nil(LangId.new("IG-NG").inspect.index("ig-NG"))
    assert_not_nil(LangId.new(0x0470).inspect.index("Igbo (Nigeria)"))
    assert_equal(0x0078, LangId.ii.to_i)
    assert_equal(LangId.ii, LangId.new("ii"))
    assert_not_nil(LangId.new("II").inspect.index("ii"))
    assert_not_nil(LangId.new(0x0078).inspect.index("Yi"))
    assert_equal(0x0478, LangId.ii_CN.to_i)
    assert_equal(LangId.ii_CN, LangId.new("ii-CN"))
    assert_not_nil(LangId.new("II-CN").inspect.index("ii-CN"))
    assert_not_nil(LangId.new(0x0478).inspect.index("Yi (PRC)"))
    assert_equal(0x000f, LangId.is.to_i)
    assert_equal(LangId.is, LangId.new("is"))
    assert_not_nil(LangId.new("IS").inspect.index("is"))
    assert_not_nil(LangId.new(0x000f).inspect.index("Icelandic"))
    assert_equal(0x040f, LangId.is_IS.to_i)
    assert_equal(LangId.is_IS, LangId.new("is-IS"))
    assert_not_nil(LangId.new("IS-IS").inspect.index("is-IS"))
    assert_not_nil(LangId.new(0x040f).inspect.index("Icelandic (Iceland)"))
    assert_equal(0x0010, LangId.it.to_i)
    assert_equal(LangId.it, LangId.new("it"))
    assert_not_nil(LangId.new("IT").inspect.index("it"))
    assert_not_nil(LangId.new(0x0010).inspect.index("Italian"))
    assert_equal(0x0810, LangId.it_CH.to_i)
    assert_equal(LangId.it_CH, LangId.new("it-CH"))
    assert_not_nil(LangId.new("IT-CH").inspect.index("it-CH"))
    assert_not_nil(LangId.new(0x0810).inspect.index("Italian (Switzerland)"))
    assert_equal(0x0410, LangId.it_IT.to_i)
    assert_equal(LangId.it_IT, LangId.new("it-IT"))
    assert_not_nil(LangId.new("IT-IT").inspect.index("it-IT"))
    assert_not_nil(LangId.new(0x0410).inspect.index("Italian (Italy)"))
    assert_equal(0x005d, LangId.iu.to_i)
    assert_equal(LangId.iu, LangId.new("iu"))
    assert_not_nil(LangId.new("IU").inspect.index("iu"))
    assert_not_nil(LangId.new(0x005d).inspect.index("Inuktitut"))
    assert_equal(0x785d, LangId.iu_Cans.to_i)
    assert_equal(LangId.iu_Cans, LangId.new("iu-Cans"))
    assert_not_nil(LangId.new("IU-CANS").inspect.index("iu-Cans"))
    assert_not_nil(LangId.new(0x785d).inspect.index("Inuktitut (Syllabics)"))
    assert_equal(0x045d, LangId.iu_Cans_CA.to_i)
    assert_equal(LangId.iu_Cans_CA, LangId.new("iu-Cans-CA"))
    assert_not_nil(LangId.new("IU-CANS-CA").inspect.index("iu-Cans-CA"))
    assert_not_nil(LangId.new(0x045d).inspect.index("Inuktitut (Syllabics, Canada)"))
    assert_equal(0x7c5d, LangId.iu_Latn.to_i)
    assert_equal(LangId.iu_Latn, LangId.new("iu-Latn"))
    assert_not_nil(LangId.new("IU-LATN").inspect.index("iu-Latn"))
    assert_not_nil(LangId.new(0x7c5d).inspect.index("Inuktitut (Latin)"))
    assert_equal(0x085d, LangId.iu_Latn_CA.to_i)
    assert_equal(LangId.iu_Latn_CA, LangId.new("iu-Latn-CA"))
    assert_not_nil(LangId.new("IU-LATN-CA").inspect.index("iu-Latn-CA"))
    assert_not_nil(LangId.new(0x085d).inspect.index("Inuktitut (Latin, Canada)"))
    assert_equal(0x0011, LangId.ja.to_i)
    assert_equal(LangId.ja, LangId.new("ja"))
    assert_not_nil(LangId.new("JA").inspect.index("ja"))
    assert_not_nil(LangId.new(0x0011).inspect.index("Japanese"))
    assert_equal(0x0411, LangId.ja_JP.to_i)
    assert_equal(LangId.ja_JP, LangId.new("ja-JP"))
    assert_not_nil(LangId.new("JA-JP").inspect.index("ja-JP"))
    assert_not_nil(LangId.new(0x0411).inspect.index("Japanese (Japan)"))
    assert_equal(0x0037, LangId.ka.to_i)
    assert_equal(LangId.ka, LangId.new("ka"))
    assert_not_nil(LangId.new("KA").inspect.index("ka"))
    assert_not_nil(LangId.new(0x0037).inspect.index("Georgian"))
    assert_equal(0x0437, LangId.ka_GE.to_i)
    assert_equal(LangId.ka_GE, LangId.new("ka-GE"))
    assert_not_nil(LangId.new("KA-GE").inspect.index("ka-GE"))
    assert_not_nil(LangId.new(0x0437).inspect.index("Georgian (Georgia)"))
    assert_equal(0x003f, LangId.kk.to_i)
    assert_equal(LangId.kk, LangId.new("kk"))
    assert_not_nil(LangId.new("KK").inspect.index("kk"))
    assert_not_nil(LangId.new(0x003f).inspect.index("Kazakh"))
    assert_equal(0x043f, LangId.kk_KZ.to_i)
    assert_equal(LangId.kk_KZ, LangId.new("kk-KZ"))
    assert_not_nil(LangId.new("KK-KZ").inspect.index("kk-KZ"))
    assert_not_nil(LangId.new(0x043f).inspect.index("Kazakh (Kazakhstan)"))
    assert_equal(0x006f, LangId.kl.to_i)
    assert_equal(LangId.kl, LangId.new("kl"))
    assert_not_nil(LangId.new("KL").inspect.index("kl"))
    assert_not_nil(LangId.new(0x006f).inspect.index("Greenlandic"))
    assert_equal(0x046f, LangId.kl_GL.to_i)
    assert_equal(LangId.kl_GL, LangId.new("kl-GL"))
    assert_not_nil(LangId.new("KL-GL").inspect.index("kl-GL"))
    assert_not_nil(LangId.new(0x046f).inspect.index("Greenlandic (Greenland)"))
    assert_equal(0x0053, LangId.km.to_i)
    assert_equal(LangId.km, LangId.new("km"))
    assert_not_nil(LangId.new("KM").inspect.index("km"))
    assert_not_nil(LangId.new(0x0053).inspect.index("Khmer"))
    assert_equal(0x0453, LangId.km_KH.to_i)
    assert_equal(LangId.km_KH, LangId.new("km-KH"))
    assert_not_nil(LangId.new("KM-KH").inspect.index("km-KH"))
    assert_not_nil(LangId.new(0x0453).inspect.index("Khmer (Cambodia)"))
    assert_equal(0x004b, LangId.kn.to_i)
    assert_equal(LangId.kn, LangId.new("kn"))
    assert_not_nil(LangId.new("KN").inspect.index("kn"))
    assert_not_nil(LangId.new(0x004b).inspect.index("Kannada"))
    assert_equal(0x044b, LangId.kn_IN.to_i)
    assert_equal(LangId.kn_IN, LangId.new("kn-IN"))
    assert_not_nil(LangId.new("KN-IN").inspect.index("kn-IN"))
    assert_not_nil(LangId.new(0x044b).inspect.index("Kannada (India)"))
    assert_equal(0x0012, LangId.ko.to_i)
    assert_equal(LangId.ko, LangId.new("ko"))
    assert_not_nil(LangId.new("KO").inspect.index("ko"))
    assert_not_nil(LangId.new(0x0012).inspect.index("Korean"))
    assert_equal(0x0412, LangId.ko_KR.to_i)
    assert_equal(LangId.ko_KR, LangId.new("ko-KR"))
    assert_not_nil(LangId.new("KO-KR").inspect.index("ko-KR"))
    assert_not_nil(LangId.new(0x0412).inspect.index("Korean (Korea)"))
    assert_equal(0x0057, LangId.kok.to_i)
    assert_equal(LangId.kok, LangId.new("kok"))
    assert_not_nil(LangId.new("KOK").inspect.index("kok"))
    assert_not_nil(LangId.new(0x0057).inspect.index("Konkani"))
    assert_equal(0x0457, LangId.kok_IN.to_i)
    assert_equal(LangId.kok_IN, LangId.new("kok-IN"))
    assert_not_nil(LangId.new("KOK-IN").inspect.index("kok-IN"))
    assert_not_nil(LangId.new(0x0457).inspect.index("Konkani (India)"))
    assert_equal(0x0040, LangId.ky.to_i)
    assert_equal(LangId.ky, LangId.new("ky"))
    assert_not_nil(LangId.new("KY").inspect.index("ky"))
    assert_not_nil(LangId.new(0x0040).inspect.index("Kyrgyz"))
    assert_equal(0x0440, LangId.ky_KG.to_i)
    assert_equal(LangId.ky_KG, LangId.new("ky-KG"))
    assert_not_nil(LangId.new("KY-KG").inspect.index("ky-KG"))
    assert_not_nil(LangId.new(0x0440).inspect.index("Kyrgyz (Kyrgyzstan)"))
    assert_equal(0x006e, LangId.lb.to_i)
    assert_equal(LangId.lb, LangId.new("lb"))
    assert_not_nil(LangId.new("LB").inspect.index("lb"))
    assert_not_nil(LangId.new(0x006e).inspect.index("Luxembourgish"))
    assert_equal(0x046e, LangId.lb_LU.to_i)
    assert_equal(LangId.lb_LU, LangId.new("lb-LU"))
    assert_not_nil(LangId.new("LB-LU").inspect.index("lb-LU"))
    assert_not_nil(LangId.new(0x046e).inspect.index("Luxembourgish (Luxembourg)"))
    assert_equal(0x0054, LangId.lo.to_i)
    assert_equal(LangId.lo, LangId.new("lo"))
    assert_not_nil(LangId.new("LO").inspect.index("lo"))
    assert_not_nil(LangId.new(0x0054).inspect.index("Lao"))
    assert_equal(0x0454, LangId.lo_LA.to_i)
    assert_equal(LangId.lo_LA, LangId.new("lo-LA"))
    assert_not_nil(LangId.new("LO-LA").inspect.index("lo-LA"))
    assert_not_nil(LangId.new(0x0454).inspect.index("Lao (Lao P.D.R.)"))
    assert_equal(0x0027, LangId.lt.to_i)
    assert_equal(LangId.lt, LangId.new("lt"))
    assert_not_nil(LangId.new("LT").inspect.index("lt"))
    assert_not_nil(LangId.new(0x0027).inspect.index("Lithuanian"))
    assert_equal(0x0427, LangId.lt_LT.to_i)
    assert_equal(LangId.lt_LT, LangId.new("lt-LT"))
    assert_not_nil(LangId.new("LT-LT").inspect.index("lt-LT"))
    assert_not_nil(LangId.new(0x0427).inspect.index("Lithuanian (Lithuania)"))
    assert_equal(0x0026, LangId.lv.to_i)
    assert_equal(LangId.lv, LangId.new("lv"))
    assert_not_nil(LangId.new("LV").inspect.index("lv"))
    assert_not_nil(LangId.new(0x0026).inspect.index("Latvian"))
    assert_equal(0x0426, LangId.lv_LV.to_i)
    assert_equal(LangId.lv_LV, LangId.new("lv-LV"))
    assert_not_nil(LangId.new("LV-LV").inspect.index("lv-LV"))
    assert_not_nil(LangId.new(0x0426).inspect.index("Latvian (Latvia)"))
    assert_equal(0x0081, LangId.mi.to_i)
    assert_equal(LangId.mi, LangId.new("mi"))
    assert_not_nil(LangId.new("MI").inspect.index("mi"))
    assert_not_nil(LangId.new(0x0081).inspect.index("Maori"))
    assert_equal(0x0481, LangId.mi_NZ.to_i)
    assert_equal(LangId.mi_NZ, LangId.new("mi-NZ"))
    assert_not_nil(LangId.new("MI-NZ").inspect.index("mi-NZ"))
    assert_not_nil(LangId.new(0x0481).inspect.index("Maori (New Zealand)"))
    assert_equal(0x002f, LangId.mk.to_i)
    assert_equal(LangId.mk, LangId.new("mk"))
    assert_not_nil(LangId.new("MK").inspect.index("mk"))
    assert_not_nil(LangId.new(0x002f).inspect.index("Macedonian (FYROM)"))
    assert_equal(0x042f, LangId.mk_MK.to_i)
    assert_equal(LangId.mk_MK, LangId.new("mk-MK"))
    assert_not_nil(LangId.new("MK-MK").inspect.index("mk-MK"))
    assert_not_nil(LangId.new(0x042f).inspect.index("Macedonian (Former Yugoslav Republic of Macedonia)"))
    assert_equal(0x004c, LangId.ml.to_i)
    assert_equal(LangId.ml, LangId.new("ml"))
    assert_not_nil(LangId.new("ML").inspect.index("ml"))
    assert_not_nil(LangId.new(0x004c).inspect.index("Malayalam"))
    assert_equal(0x044c, LangId.ml_IN.to_i)
    assert_equal(LangId.ml_IN, LangId.new("ml-IN"))
    assert_not_nil(LangId.new("ML-IN").inspect.index("ml-IN"))
    assert_not_nil(LangId.new(0x044c).inspect.index("Malayalam (India)"))
    assert_equal(0x0050, LangId.mn.to_i)
    assert_equal(LangId.mn, LangId.new("mn"))
    assert_not_nil(LangId.new("MN").inspect.index("mn"))
    assert_not_nil(LangId.new(0x0050).inspect.index("Mongolian"))
    assert_equal(0x7850, LangId.mn_Cyrl.to_i)
    assert_equal(LangId.mn_Cyrl, LangId.new("mn-Cyrl"))
    assert_not_nil(LangId.new("MN-CYRL").inspect.index("mn-Cyrl"))
    assert_not_nil(LangId.new(0x7850).inspect.index("Mongolian (Cyrillic)"))
    assert_equal(0x0450, LangId.mn_MN.to_i)
    assert_equal(LangId.mn_MN, LangId.new("mn-MN"))
    assert_not_nil(LangId.new("MN-MN").inspect.index("mn-MN"))
    assert_not_nil(LangId.new(0x0450).inspect.index("Mongolian (Cyrillic, Mongolia)"))
    assert_equal(0x7c50, LangId.mn_Mong.to_i)
    assert_equal(LangId.mn_Mong, LangId.new("mn-Mong"))
    assert_not_nil(LangId.new("MN-MONG").inspect.index("mn-Mong"))
    assert_not_nil(LangId.new(0x7c50).inspect.index("Mongolian (Traditional Mongolian)"))
    assert_equal(0x0850, LangId.mn_Mong_CN.to_i)
    assert_equal(LangId.mn_Mong_CN, LangId.new("mn-Mong-CN"))
    assert_not_nil(LangId.new("MN-MONG-CN").inspect.index("mn-Mong-CN"))
    assert_not_nil(LangId.new(0x0850).inspect.index("Mongolian (Traditional Mongolian, PRC)"))
    assert_equal(0x007c, LangId.moh.to_i)
    assert_equal(LangId.moh, LangId.new("moh"))
    assert_not_nil(LangId.new("MOH").inspect.index("moh"))
    assert_not_nil(LangId.new(0x007c).inspect.index("Mohawk"))
    assert_equal(0x047c, LangId.moh_CA.to_i)
    assert_equal(LangId.moh_CA, LangId.new("moh-CA"))
    assert_not_nil(LangId.new("MOH-CA").inspect.index("moh-CA"))
    assert_not_nil(LangId.new(0x047c).inspect.index("Mohawk (Mohawk)"))
    assert_equal(0x004e, LangId.mr.to_i)
    assert_equal(LangId.mr, LangId.new("mr"))
    assert_not_nil(LangId.new("MR").inspect.index("mr"))
    assert_not_nil(LangId.new(0x004e).inspect.index("Marathi"))
    assert_equal(0x044e, LangId.mr_IN.to_i)
    assert_equal(LangId.mr_IN, LangId.new("mr-IN"))
    assert_not_nil(LangId.new("MR-IN").inspect.index("mr-IN"))
    assert_not_nil(LangId.new(0x044e).inspect.index("Marathi (India)"))
    assert_equal(0x003e, LangId.ms.to_i)
    assert_equal(LangId.ms, LangId.new("ms"))
    assert_not_nil(LangId.new("MS").inspect.index("ms"))
    assert_not_nil(LangId.new(0x003e).inspect.index("Malay"))
    assert_equal(0x083e, LangId.ms_BN.to_i)
    assert_equal(LangId.ms_BN, LangId.new("ms-BN"))
    assert_not_nil(LangId.new("MS-BN").inspect.index("ms-BN"))
    assert_not_nil(LangId.new(0x083e).inspect.index("Malay (Brunei Darussalam)"))
    assert_equal(0x043e, LangId.ms_MY.to_i)
    assert_equal(LangId.ms_MY, LangId.new("ms-MY"))
    assert_not_nil(LangId.new("MS-MY").inspect.index("ms-MY"))
    assert_not_nil(LangId.new(0x043e).inspect.index("Malay (Malaysia)"))
    assert_equal(0x003a, LangId.mt.to_i)
    assert_equal(LangId.mt, LangId.new("mt"))
    assert_not_nil(LangId.new("MT").inspect.index("mt"))
    assert_not_nil(LangId.new(0x003a).inspect.index("Maltese"))
    assert_equal(0x043a, LangId.mt_MT.to_i)
    assert_equal(LangId.mt_MT, LangId.new("mt-MT"))
    assert_not_nil(LangId.new("MT-MT").inspect.index("mt-MT"))
    assert_not_nil(LangId.new(0x043a).inspect.index("Maltese (Malta)"))
    assert_equal(0x7c14, LangId.nb.to_i)
    assert_equal(LangId.nb, LangId.new("nb"))
    assert_not_nil(LangId.new("NB").inspect.index("nb"))
    assert_not_nil(LangId.new(0x7c14).inspect.index("Norwegian (Bokmål)"))
    assert_equal(0x0414, LangId.nb_NO.to_i)
    assert_equal(LangId.nb_NO, LangId.new("nb-NO"))
    assert_not_nil(LangId.new("NB-NO").inspect.index("nb-NO"))
    assert_not_nil(LangId.new(0x0414).inspect.index("Norwegian, Bokmål (Norway)"))
    assert_equal(0x0061, LangId.ne.to_i)
    assert_equal(LangId.ne, LangId.new("ne"))
    assert_not_nil(LangId.new("NE").inspect.index("ne"))
    assert_not_nil(LangId.new(0x0061).inspect.index("Nepali"))
    assert_equal(0x0461, LangId.ne_NP.to_i)
    assert_equal(LangId.ne_NP, LangId.new("ne-NP"))
    assert_not_nil(LangId.new("NE-NP").inspect.index("ne-NP"))
    assert_not_nil(LangId.new(0x0461).inspect.index("Nepali (Nepal)"))
    assert_equal(0x0013, LangId.nl.to_i)
    assert_equal(LangId.nl, LangId.new("nl"))
    assert_not_nil(LangId.new("NL").inspect.index("nl"))
    assert_not_nil(LangId.new(0x0013).inspect.index("Dutch"))
    assert_equal(0x0813, LangId.nl_BE.to_i)
    assert_equal(LangId.nl_BE, LangId.new("nl-BE"))
    assert_not_nil(LangId.new("NL-BE").inspect.index("nl-BE"))
    assert_not_nil(LangId.new(0x0813).inspect.index("Dutch (Belgium)"))
    assert_equal(0x0413, LangId.nl_NL.to_i)
    assert_equal(LangId.nl_NL, LangId.new("nl-NL"))
    assert_not_nil(LangId.new("NL-NL").inspect.index("nl-NL"))
    assert_not_nil(LangId.new(0x0413).inspect.index("Dutch (Netherlands)"))
    assert_equal(0x7814, LangId.nn.to_i)
    assert_equal(LangId.nn, LangId.new("nn"))
    assert_not_nil(LangId.new("NN").inspect.index("nn"))
    assert_not_nil(LangId.new(0x7814).inspect.index("Norwegian (Nynorsk)"))
    assert_equal(0x0814, LangId.nn_NO.to_i)
    assert_equal(LangId.nn_NO, LangId.new("nn-NO"))
    assert_not_nil(LangId.new("NN-NO").inspect.index("nn-NO"))
    assert_not_nil(LangId.new(0x0814).inspect.index("Norwegian, Nynorsk (Norway)"))
    assert_equal(0x0014, LangId.no.to_i)
    assert_equal(LangId.no, LangId.new("no"))
    assert_not_nil(LangId.new("NO").inspect.index("no"))
    assert_not_nil(LangId.new(0x0014).inspect.index("Norwegian"))
    assert_equal(0x006c, LangId.nso.to_i)
    assert_equal(LangId.nso, LangId.new("nso"))
    assert_not_nil(LangId.new("NSO").inspect.index("nso"))
    assert_not_nil(LangId.new(0x006c).inspect.index("Sesotho sa Leboa"))
    assert_equal(0x046c, LangId.nso_ZA.to_i)
    assert_equal(LangId.nso_ZA, LangId.new("nso-ZA"))
    assert_not_nil(LangId.new("NSO-ZA").inspect.index("nso-ZA"))
    assert_not_nil(LangId.new(0x046c).inspect.index("Sesotho sa Leboa (South Africa)"))
    assert_equal(0x0082, LangId.oc.to_i)
    assert_equal(LangId.oc, LangId.new("oc"))
    assert_not_nil(LangId.new("OC").inspect.index("oc"))
    assert_not_nil(LangId.new(0x0082).inspect.index("Occitan"))
    assert_equal(0x0482, LangId.oc_FR.to_i)
    assert_equal(LangId.oc_FR, LangId.new("oc-FR"))
    assert_not_nil(LangId.new("OC-FR").inspect.index("oc-FR"))
    assert_not_nil(LangId.new(0x0482).inspect.index("Occitan (France)"))
    assert_equal(0x0048, LangId.or.to_i)
    assert_equal(LangId.or, LangId.new("or"))
    assert_not_nil(LangId.new("OR").inspect.index("or"))
    assert_not_nil(LangId.new(0x0048).inspect.index("Oriya"))
    assert_equal(0x0448, LangId.or_IN.to_i)
    assert_equal(LangId.or_IN, LangId.new("or-IN"))
    assert_not_nil(LangId.new("OR-IN").inspect.index("or-IN"))
    assert_not_nil(LangId.new(0x0448).inspect.index("Oriya (India)"))
    assert_equal(0x0046, LangId.pa.to_i)
    assert_equal(LangId.pa, LangId.new("pa"))
    assert_not_nil(LangId.new("PA").inspect.index("pa"))
    assert_not_nil(LangId.new(0x0046).inspect.index("Punjabi"))
    assert_equal(0x0446, LangId.pa_IN.to_i)
    assert_equal(LangId.pa_IN, LangId.new("pa-IN"))
    assert_not_nil(LangId.new("PA-IN").inspect.index("pa-IN"))
    assert_not_nil(LangId.new(0x0446).inspect.index("Punjabi (India)"))
    assert_equal(0x0015, LangId.pl.to_i)
    assert_equal(LangId.pl, LangId.new("pl"))
    assert_not_nil(LangId.new("PL").inspect.index("pl"))
    assert_not_nil(LangId.new(0x0015).inspect.index("Polish"))
    assert_equal(0x0415, LangId.pl_PL.to_i)
    assert_equal(LangId.pl_PL, LangId.new("pl-PL"))
    assert_not_nil(LangId.new("PL-PL").inspect.index("pl-PL"))
    assert_not_nil(LangId.new(0x0415).inspect.index("Polish (Poland)"))
    assert_equal(0x008c, LangId.prs.to_i)
    assert_equal(LangId.prs, LangId.new("prs"))
    assert_not_nil(LangId.new("PRS").inspect.index("prs"))
    assert_not_nil(LangId.new(0x008c).inspect.index("Dari"))
    assert_equal(0x048c, LangId.prs_AF.to_i)
    assert_equal(LangId.prs_AF, LangId.new("prs-AF"))
    assert_not_nil(LangId.new("PRS-AF").inspect.index("prs-AF"))
    assert_not_nil(LangId.new(0x048c).inspect.index("Dari (Afghanistan)"))
    assert_equal(0x0063, LangId.ps.to_i)
    assert_equal(LangId.ps, LangId.new("ps"))
    assert_not_nil(LangId.new("PS").inspect.index("ps"))
    assert_not_nil(LangId.new(0x0063).inspect.index("Pashto"))
    assert_equal(0x0463, LangId.ps_AF.to_i)
    assert_equal(LangId.ps_AF, LangId.new("ps-AF"))
    assert_not_nil(LangId.new("PS-AF").inspect.index("ps-AF"))
    assert_not_nil(LangId.new(0x0463).inspect.index("Pashto (Afghanistan)"))
    assert_equal(0x0016, LangId.pt.to_i)
    assert_equal(LangId.pt, LangId.new("pt"))
    assert_not_nil(LangId.new("PT").inspect.index("pt"))
    assert_not_nil(LangId.new(0x0016).inspect.index("Portuguese"))
    assert_equal(0x0416, LangId.pt_BR.to_i)
    assert_equal(LangId.pt_BR, LangId.new("pt-BR"))
    assert_not_nil(LangId.new("PT-BR").inspect.index("pt-BR"))
    assert_not_nil(LangId.new(0x0416).inspect.index("Portuguese (Brazil)"))
    assert_equal(0x0816, LangId.pt_PT.to_i)
    assert_equal(LangId.pt_PT, LangId.new("pt-PT"))
    assert_not_nil(LangId.new("PT-PT").inspect.index("pt-PT"))
    assert_not_nil(LangId.new(0x0816).inspect.index("Portuguese (Portugal)"))
    assert_equal(0x0086, LangId.qut.to_i)
    assert_equal(LangId.qut, LangId.new("qut"))
    assert_not_nil(LangId.new("QUT").inspect.index("qut"))
    assert_not_nil(LangId.new(0x0086).inspect.index("K'iche"))
    assert_equal(0x0486, LangId.qut_GT.to_i)
    assert_equal(LangId.qut_GT, LangId.new("qut-GT"))
    assert_not_nil(LangId.new("QUT-GT").inspect.index("qut-GT"))
    assert_not_nil(LangId.new(0x0486).inspect.index("K'iche (Guatemala)"))
    assert_equal(0x006b, LangId.quz.to_i)
    assert_equal(LangId.quz, LangId.new("quz"))
    assert_not_nil(LangId.new("QUZ").inspect.index("quz"))
    assert_not_nil(LangId.new(0x006b).inspect.index("Quechua"))
    assert_equal(0x046b, LangId.quz_BO.to_i)
    assert_equal(LangId.quz_BO, LangId.new("quz-BO"))
    assert_not_nil(LangId.new("QUZ-BO").inspect.index("quz-BO"))
    assert_not_nil(LangId.new(0x046b).inspect.index("Quechua (Bolivia)"))
    assert_equal(0x086b, LangId.quz_EC.to_i)
    assert_equal(LangId.quz_EC, LangId.new("quz-EC"))
    assert_not_nil(LangId.new("QUZ-EC").inspect.index("quz-EC"))
    assert_not_nil(LangId.new(0x086b).inspect.index("Quechua (Ecuador)"))
    assert_equal(0x0c6b, LangId.quz_PE.to_i)
    assert_equal(LangId.quz_PE, LangId.new("quz-PE"))
    assert_not_nil(LangId.new("QUZ-PE").inspect.index("quz-PE"))
    assert_not_nil(LangId.new(0x0c6b).inspect.index("Quechua (Peru)"))
    assert_equal(0x0017, LangId.rm.to_i)
    assert_equal(LangId.rm, LangId.new("rm"))
    assert_not_nil(LangId.new("RM").inspect.index("rm"))
    assert_not_nil(LangId.new(0x0017).inspect.index("Romansh"))
    assert_equal(0x0417, LangId.rm_CH.to_i)
    assert_equal(LangId.rm_CH, LangId.new("rm-CH"))
    assert_not_nil(LangId.new("RM-CH").inspect.index("rm-CH"))
    assert_not_nil(LangId.new(0x0417).inspect.index("Romansh (Switzerland)"))
    assert_equal(0x0018, LangId.ro.to_i)
    assert_equal(LangId.ro, LangId.new("ro"))
    assert_not_nil(LangId.new("RO").inspect.index("ro"))
    assert_not_nil(LangId.new(0x0018).inspect.index("Romanian"))
    assert_equal(0x0418, LangId.ro_RO.to_i)
    assert_equal(LangId.ro_RO, LangId.new("ro-RO"))
    assert_not_nil(LangId.new("RO-RO").inspect.index("ro-RO"))
    assert_not_nil(LangId.new(0x0418).inspect.index("Romanian (Romania)"))
    assert_equal(0x0019, LangId.ru.to_i)
    assert_equal(LangId.ru, LangId.new("ru"))
    assert_not_nil(LangId.new("RU").inspect.index("ru"))
    assert_not_nil(LangId.new(0x0019).inspect.index("Russian"))
    assert_equal(0x0419, LangId.ru_RU.to_i)
    assert_equal(LangId.ru_RU, LangId.new("ru-RU"))
    assert_not_nil(LangId.new("RU-RU").inspect.index("ru-RU"))
    assert_not_nil(LangId.new(0x0419).inspect.index("Russian (Russia)"))
    assert_equal(0x0087, LangId.rw.to_i)
    assert_equal(LangId.rw, LangId.new("rw"))
    assert_not_nil(LangId.new("RW").inspect.index("rw"))
    assert_not_nil(LangId.new(0x0087).inspect.index("Kinyarwanda"))
    assert_equal(0x0487, LangId.rw_RW.to_i)
    assert_equal(LangId.rw_RW, LangId.new("rw-RW"))
    assert_not_nil(LangId.new("RW-RW").inspect.index("rw-RW"))
    assert_not_nil(LangId.new(0x0487).inspect.index("Kinyarwanda (Rwanda)"))
    assert_equal(0x004f, LangId.sa.to_i)
    assert_equal(LangId.sa, LangId.new("sa"))
    assert_not_nil(LangId.new("SA").inspect.index("sa"))
    assert_not_nil(LangId.new(0x004f).inspect.index("Sanskrit"))
    assert_equal(0x044f, LangId.sa_IN.to_i)
    assert_equal(LangId.sa_IN, LangId.new("sa-IN"))
    assert_not_nil(LangId.new("SA-IN").inspect.index("sa-IN"))
    assert_not_nil(LangId.new(0x044f).inspect.index("Sanskrit (India)"))
    assert_equal(0x0085, LangId.sah.to_i)
    assert_equal(LangId.sah, LangId.new("sah"))
    assert_not_nil(LangId.new("SAH").inspect.index("sah"))
    assert_not_nil(LangId.new(0x0085).inspect.index("Yakut"))
    assert_equal(0x0485, LangId.sah_RU.to_i)
    assert_equal(LangId.sah_RU, LangId.new("sah-RU"))
    assert_not_nil(LangId.new("SAH-RU").inspect.index("sah-RU"))
    assert_not_nil(LangId.new(0x0485).inspect.index("Yakut (Russia)"))
    assert_equal(0x003b, LangId.se.to_i)
    assert_equal(LangId.se, LangId.new("se"))
    assert_not_nil(LangId.new("SE").inspect.index("se"))
    assert_not_nil(LangId.new(0x003b).inspect.index("Sami (Northern)"))
    assert_equal(0x0c3b, LangId.se_FI.to_i)
    assert_equal(LangId.se_FI, LangId.new("se-FI"))
    assert_not_nil(LangId.new("SE-FI").inspect.index("se-FI"))
    assert_not_nil(LangId.new(0x0c3b).inspect.index("Sami, Northern (Finland)"))
    assert_equal(0x043b, LangId.se_NO.to_i)
    assert_equal(LangId.se_NO, LangId.new("se-NO"))
    assert_not_nil(LangId.new("SE-NO").inspect.index("se-NO"))
    assert_not_nil(LangId.new(0x043b).inspect.index("Sami, Northern (Norway)"))
    assert_equal(0x083b, LangId.se_SE.to_i)
    assert_equal(LangId.se_SE, LangId.new("se-SE"))
    assert_not_nil(LangId.new("SE-SE").inspect.index("se-SE"))
    assert_not_nil(LangId.new(0x083b).inspect.index("Sami, Northern (Sweden)"))
    assert_equal(0x005b, LangId.si.to_i)
    assert_equal(LangId.si, LangId.new("si"))
    assert_not_nil(LangId.new("SI").inspect.index("si"))
    assert_not_nil(LangId.new(0x005b).inspect.index("Sinhala"))
    assert_equal(0x045b, LangId.si_LK.to_i)
    assert_equal(LangId.si_LK, LangId.new("si-LK"))
    assert_not_nil(LangId.new("SI-LK").inspect.index("si-LK"))
    assert_not_nil(LangId.new(0x045b).inspect.index("Sinhala (Sri Lanka)"))
    assert_equal(0x001b, LangId.sk.to_i)
    assert_equal(LangId.sk, LangId.new("sk"))
    assert_not_nil(LangId.new("SK").inspect.index("sk"))
    assert_not_nil(LangId.new(0x001b).inspect.index("Slovak"))
    assert_equal(0x041b, LangId.sk_SK.to_i)
    assert_equal(LangId.sk_SK, LangId.new("sk-SK"))
    assert_not_nil(LangId.new("SK-SK").inspect.index("sk-SK"))
    assert_not_nil(LangId.new(0x041b).inspect.index("Slovak (Slovakia)"))
    assert_equal(0x0024, LangId.sl.to_i)
    assert_equal(LangId.sl, LangId.new("sl"))
    assert_not_nil(LangId.new("SL").inspect.index("sl"))
    assert_not_nil(LangId.new(0x0024).inspect.index("Slovenian"))
    assert_equal(0x0424, LangId.sl_SI.to_i)
    assert_equal(LangId.sl_SI, LangId.new("sl-SI"))
    assert_not_nil(LangId.new("SL-SI").inspect.index("sl-SI"))
    assert_not_nil(LangId.new(0x0424).inspect.index("Slovenian (Slovenia)"))
    assert_equal(0x783b, LangId.sma.to_i)
    assert_equal(LangId.sma, LangId.new("sma"))
    assert_not_nil(LangId.new("SMA").inspect.index("sma"))
    assert_not_nil(LangId.new(0x783b).inspect.index("Sami (Southern)"))
    assert_equal(0x183b, LangId.sma_NO.to_i)
    assert_equal(LangId.sma_NO, LangId.new("sma-NO"))
    assert_not_nil(LangId.new("SMA-NO").inspect.index("sma-NO"))
    assert_not_nil(LangId.new(0x183b).inspect.index("Sami, Southern (Norway)"))
    assert_equal(0x1c3b, LangId.sma_SE.to_i)
    assert_equal(LangId.sma_SE, LangId.new("sma-SE"))
    assert_not_nil(LangId.new("SMA-SE").inspect.index("sma-SE"))
    assert_not_nil(LangId.new(0x1c3b).inspect.index("Sami, Southern (Sweden)"))
    assert_equal(0x7c3b, LangId.smj.to_i)
    assert_equal(LangId.smj, LangId.new("smj"))
    assert_not_nil(LangId.new("SMJ").inspect.index("smj"))
    assert_not_nil(LangId.new(0x7c3b).inspect.index("Sami (Lule)"))
    assert_equal(0x103b, LangId.smj_NO.to_i)
    assert_equal(LangId.smj_NO, LangId.new("smj-NO"))
    assert_not_nil(LangId.new("SMJ-NO").inspect.index("smj-NO"))
    assert_not_nil(LangId.new(0x103b).inspect.index("Sami, Lule (Norway)"))
    assert_equal(0x143b, LangId.smj_SE.to_i)
    assert_equal(LangId.smj_SE, LangId.new("smj-SE"))
    assert_not_nil(LangId.new("SMJ-SE").inspect.index("smj-SE"))
    assert_not_nil(LangId.new(0x143b).inspect.index("Sami, Lule (Sweden)"))
    assert_equal(0x703b, LangId.smn.to_i)
    assert_equal(LangId.smn, LangId.new("smn"))
    assert_not_nil(LangId.new("SMN").inspect.index("smn"))
    assert_not_nil(LangId.new(0x703b).inspect.index("Sami (Inari)"))
    assert_equal(0x243b, LangId.smn_FI.to_i)
    assert_equal(LangId.smn_FI, LangId.new("smn-FI"))
    assert_not_nil(LangId.new("SMN-FI").inspect.index("smn-FI"))
    assert_not_nil(LangId.new(0x243b).inspect.index("Sami, Inari (Finland)"))
    assert_equal(0x743b, LangId.sms.to_i)
    assert_equal(LangId.sms, LangId.new("sms"))
    assert_not_nil(LangId.new("SMS").inspect.index("sms"))
    assert_not_nil(LangId.new(0x743b).inspect.index("Sami (Skolt)"))
    assert_equal(0x203b, LangId.sms_FI.to_i)
    assert_equal(LangId.sms_FI, LangId.new("sms-FI"))
    assert_not_nil(LangId.new("SMS-FI").inspect.index("sms-FI"))
    assert_not_nil(LangId.new(0x203b).inspect.index("Sami, Skolt (Finland)"))
    assert_equal(0x001c, LangId.sq.to_i)
    assert_equal(LangId.sq, LangId.new("sq"))
    assert_not_nil(LangId.new("SQ").inspect.index("sq"))
    assert_not_nil(LangId.new(0x001c).inspect.index("Albanian"))
    assert_equal(0x041c, LangId.sq_AL.to_i)
    assert_equal(LangId.sq_AL, LangId.new("sq-AL"))
    assert_not_nil(LangId.new("SQ-AL").inspect.index("sq-AL"))
    assert_not_nil(LangId.new(0x041c).inspect.index("Albanian (Albania)"))
    assert_equal(0x7c1a, LangId.sr.to_i)
    assert_equal(LangId.sr, LangId.new("sr"))
    assert_not_nil(LangId.new("SR").inspect.index("sr"))
    assert_not_nil(LangId.new(0x7c1a).inspect.index("Serbian"))
    assert_equal(0x6c1a, LangId.sr_Cyrl.to_i)
    assert_equal(LangId.sr_Cyrl, LangId.new("sr-Cyrl"))
    assert_not_nil(LangId.new("SR-CYRL").inspect.index("sr-Cyrl"))
    assert_not_nil(LangId.new(0x6c1a).inspect.index("Serbian (Cyrillic)"))
    assert_equal(0x1c1a, LangId.sr_Cyrl_BA.to_i)
    assert_equal(LangId.sr_Cyrl_BA, LangId.new("sr-Cyrl-BA"))
    assert_not_nil(LangId.new("SR-CYRL-BA").inspect.index("sr-Cyrl-BA"))
    assert_not_nil(LangId.new(0x1c1a).inspect.index("Serbian (Cyrillic, Bosnia and Herzegovina)"))
    assert_equal(0x0c1a, LangId.sr_Cyrl_CS.to_i)
    assert_equal(LangId.sr_Cyrl_CS, LangId.new("sr-Cyrl-CS"))
    assert_not_nil(LangId.new("SR-CYRL-CS").inspect.index("sr-Cyrl-CS"))
    assert_not_nil(LangId.new(0x0c1a).inspect.index("Serbian (Cyrillic, Serbia and Montenegro (Former))"))
    assert_equal(0x301a, LangId.sr_Cyrl_ME.to_i)
    assert_equal(LangId.sr_Cyrl_ME, LangId.new("sr-Cyrl-ME"))
    assert_not_nil(LangId.new("SR-CYRL-ME").inspect.index("sr-Cyrl-ME"))
    assert_not_nil(LangId.new(0x301a).inspect.index("Serbian (Cyrillic, Montenegro)"))
    assert_equal(0x281a, LangId.sr_Cyrl_RS.to_i)
    assert_equal(LangId.sr_Cyrl_RS, LangId.new("sr-Cyrl-RS"))
    assert_not_nil(LangId.new("SR-CYRL-RS").inspect.index("sr-Cyrl-RS"))
    assert_not_nil(LangId.new(0x281a).inspect.index("Serbian (Cyrillic, Serbia)"))
    assert_equal(0x701a, LangId.sr_Latn.to_i)
    assert_equal(LangId.sr_Latn, LangId.new("sr-Latn"))
    assert_not_nil(LangId.new("SR-LATN").inspect.index("sr-Latn"))
    assert_not_nil(LangId.new(0x701a).inspect.index("Serbian (Latin)"))
    assert_equal(0x181a, LangId.sr_Latn_BA.to_i)
    assert_equal(LangId.sr_Latn_BA, LangId.new("sr-Latn-BA"))
    assert_not_nil(LangId.new("SR-LATN-BA").inspect.index("sr-Latn-BA"))
    assert_not_nil(LangId.new(0x181a).inspect.index("Serbian (Latin, Bosnia and Herzegovina)"))
    assert_equal(0x081a, LangId.sr_Latn_CS.to_i)
    assert_equal(LangId.sr_Latn_CS, LangId.new("sr-Latn-CS"))
    assert_not_nil(LangId.new("SR-LATN-CS").inspect.index("sr-Latn-CS"))
    assert_not_nil(LangId.new(0x081a).inspect.index("Serbian (Latin, Serbia and Montenegro (Former))"))
    assert_equal(0x2c1a, LangId.sr_Latn_ME.to_i)
    assert_equal(LangId.sr_Latn_ME, LangId.new("sr-Latn-ME"))
    assert_not_nil(LangId.new("SR-LATN-ME").inspect.index("sr-Latn-ME"))
    assert_not_nil(LangId.new(0x2c1a).inspect.index("Serbian (Latin, Montenegro)"))
    assert_equal(0x241a, LangId.sr_Latn_RS.to_i)
    assert_equal(LangId.sr_Latn_RS, LangId.new("sr-Latn-RS"))
    assert_not_nil(LangId.new("SR-LATN-RS").inspect.index("sr-Latn-RS"))
    assert_not_nil(LangId.new(0x241a).inspect.index("Serbian (Latin, Serbia)"))
    assert_equal(0x001d, LangId.sv.to_i)
    assert_equal(LangId.sv, LangId.new("sv"))
    assert_not_nil(LangId.new("SV").inspect.index("sv"))
    assert_not_nil(LangId.new(0x001d).inspect.index("Swedish"))
    assert_equal(0x081d, LangId.sv_FI.to_i)
    assert_equal(LangId.sv_FI, LangId.new("sv-FI"))
    assert_not_nil(LangId.new("SV-FI").inspect.index("sv-FI"))
    assert_not_nil(LangId.new(0x081d).inspect.index("Swedish (Finland)"))
    assert_equal(0x041d, LangId.sv_SE.to_i)
    assert_equal(LangId.sv_SE, LangId.new("sv-SE"))
    assert_not_nil(LangId.new("SV-SE").inspect.index("sv-SE"))
    assert_not_nil(LangId.new(0x041d).inspect.index("Swedish (Sweden)"))
    assert_equal(0x0041, LangId.sw.to_i)
    assert_equal(LangId.sw, LangId.new("sw"))
    assert_not_nil(LangId.new("SW").inspect.index("sw"))
    assert_not_nil(LangId.new(0x0041).inspect.index("Kiswahili"))
    assert_equal(0x0441, LangId.sw_KE.to_i)
    assert_equal(LangId.sw_KE, LangId.new("sw-KE"))
    assert_not_nil(LangId.new("SW-KE").inspect.index("sw-KE"))
    assert_not_nil(LangId.new(0x0441).inspect.index("Kiswahili (Kenya)"))
    assert_equal(0x005a, LangId.syr.to_i)
    assert_equal(LangId.syr, LangId.new("syr"))
    assert_not_nil(LangId.new("SYR").inspect.index("syr"))
    assert_not_nil(LangId.new(0x005a).inspect.index("Syriac"))
    assert_equal(0x045a, LangId.syr_SY.to_i)
    assert_equal(LangId.syr_SY, LangId.new("syr-SY"))
    assert_not_nil(LangId.new("SYR-SY").inspect.index("syr-SY"))
    assert_not_nil(LangId.new(0x045a).inspect.index("Syriac (Syria)"))
    assert_equal(0x0049, LangId.ta.to_i)
    assert_equal(LangId.ta, LangId.new("ta"))
    assert_not_nil(LangId.new("TA").inspect.index("ta"))
    assert_not_nil(LangId.new(0x0049).inspect.index("Tamil"))
    assert_equal(0x0449, LangId.ta_IN.to_i)
    assert_equal(LangId.ta_IN, LangId.new("ta-IN"))
    assert_not_nil(LangId.new("TA-IN").inspect.index("ta-IN"))
    assert_not_nil(LangId.new(0x0449).inspect.index("Tamil (India)"))
    assert_equal(0x004a, LangId.te.to_i)
    assert_equal(LangId.te, LangId.new("te"))
    assert_not_nil(LangId.new("TE").inspect.index("te"))
    assert_not_nil(LangId.new(0x004a).inspect.index("Telugu"))
    assert_equal(0x044a, LangId.te_IN.to_i)
    assert_equal(LangId.te_IN, LangId.new("te-IN"))
    assert_not_nil(LangId.new("TE-IN").inspect.index("te-IN"))
    assert_not_nil(LangId.new(0x044a).inspect.index("Telugu (India)"))
    assert_equal(0x0028, LangId.tg.to_i)
    assert_equal(LangId.tg, LangId.new("tg"))
    assert_not_nil(LangId.new("TG").inspect.index("tg"))
    assert_not_nil(LangId.new(0x0028).inspect.index("Tajik"))
    assert_equal(0x7c28, LangId.tg_Cyrl.to_i)
    assert_equal(LangId.tg_Cyrl, LangId.new("tg-Cyrl"))
    assert_not_nil(LangId.new("TG-CYRL").inspect.index("tg-Cyrl"))
    assert_not_nil(LangId.new(0x7c28).inspect.index("Tajik (Cyrillic)"))
    assert_equal(0x0428, LangId.tg_Cyrl_TJ.to_i)
    assert_equal(LangId.tg_Cyrl_TJ, LangId.new("tg-Cyrl-TJ"))
    assert_not_nil(LangId.new("TG-CYRL-TJ").inspect.index("tg-Cyrl-TJ"))
    assert_not_nil(LangId.new(0x0428).inspect.index("Tajik (Cyrillic, Tajikistan)"))
    assert_equal(0x001e, LangId.th.to_i)
    assert_equal(LangId.th, LangId.new("th"))
    assert_not_nil(LangId.new("TH").inspect.index("th"))
    assert_not_nil(LangId.new(0x001e).inspect.index("Thai"))
    assert_equal(0x041e, LangId.th_TH.to_i)
    assert_equal(LangId.th_TH, LangId.new("th-TH"))
    assert_not_nil(LangId.new("TH-TH").inspect.index("th-TH"))
    assert_not_nil(LangId.new(0x041e).inspect.index("Thai (Thailand)"))
    assert_equal(0x0042, LangId.tk.to_i)
    assert_equal(LangId.tk, LangId.new("tk"))
    assert_not_nil(LangId.new("TK").inspect.index("tk"))
    assert_not_nil(LangId.new(0x0042).inspect.index("Turkmen"))
    assert_equal(0x0442, LangId.tk_TM.to_i)
    assert_equal(LangId.tk_TM, LangId.new("tk-TM"))
    assert_not_nil(LangId.new("TK-TM").inspect.index("tk-TM"))
    assert_not_nil(LangId.new(0x0442).inspect.index("Turkmen (Turkmenistan)"))
    assert_equal(0x0032, LangId.tn.to_i)
    assert_equal(LangId.tn, LangId.new("tn"))
    assert_not_nil(LangId.new("TN").inspect.index("tn"))
    assert_not_nil(LangId.new(0x0032).inspect.index("Setswana"))
    assert_equal(0x0432, LangId.tn_ZA.to_i)
    assert_equal(LangId.tn_ZA, LangId.new("tn-ZA"))
    assert_not_nil(LangId.new("TN-ZA").inspect.index("tn-ZA"))
    assert_not_nil(LangId.new(0x0432).inspect.index("Setswana (South Africa)"))
    assert_equal(0x001f, LangId.tr.to_i)
    assert_equal(LangId.tr, LangId.new("tr"))
    assert_not_nil(LangId.new("TR").inspect.index("tr"))
    assert_not_nil(LangId.new(0x001f).inspect.index("Turkish"))
    assert_equal(0x041f, LangId.tr_TR.to_i)
    assert_equal(LangId.tr_TR, LangId.new("tr-TR"))
    assert_not_nil(LangId.new("TR-TR").inspect.index("tr-TR"))
    assert_not_nil(LangId.new(0x041f).inspect.index("Turkish (Turkey)"))
    assert_equal(0x0044, LangId.tt.to_i)
    assert_equal(LangId.tt, LangId.new("tt"))
    assert_not_nil(LangId.new("TT").inspect.index("tt"))
    assert_not_nil(LangId.new(0x0044).inspect.index("Tatar"))
    assert_equal(0x0444, LangId.tt_RU.to_i)
    assert_equal(LangId.tt_RU, LangId.new("tt-RU"))
    assert_not_nil(LangId.new("TT-RU").inspect.index("tt-RU"))
    assert_not_nil(LangId.new(0x0444).inspect.index("Tatar (Russia)"))
    assert_equal(0x005f, LangId.tzm.to_i)
    assert_equal(LangId.tzm, LangId.new("tzm"))
    assert_not_nil(LangId.new("TZM").inspect.index("tzm"))
    assert_not_nil(LangId.new(0x005f).inspect.index("Tamazight"))
    assert_equal(0x7c5f, LangId.tzm_Latn.to_i)
    assert_equal(LangId.tzm_Latn, LangId.new("tzm-Latn"))
    assert_not_nil(LangId.new("TZM-LATN").inspect.index("tzm-Latn"))
    assert_not_nil(LangId.new(0x7c5f).inspect.index("Tamazight (Latin)"))
    assert_equal(0x085f, LangId.tzm_Latn_DZ.to_i)
    assert_equal(LangId.tzm_Latn_DZ, LangId.new("tzm-Latn-DZ"))
    assert_not_nil(LangId.new("TZM-LATN-DZ").inspect.index("tzm-Latn-DZ"))
    assert_not_nil(LangId.new(0x085f).inspect.index("Tamazight (Latin, Algeria)"))
    assert_equal(0x0080, LangId.ug.to_i)
    assert_equal(LangId.ug, LangId.new("ug"))
    assert_not_nil(LangId.new("UG").inspect.index("ug"))
    assert_not_nil(LangId.new(0x0080).inspect.index("Uyghur"))
    assert_equal(0x0480, LangId.ug_CN.to_i)
    assert_equal(LangId.ug_CN, LangId.new("ug-CN"))
    assert_not_nil(LangId.new("UG-CN").inspect.index("ug-CN"))
    assert_not_nil(LangId.new(0x0480).inspect.index("Uyghur (PRC)"))
    assert_equal(0x0022, LangId.uk.to_i)
    assert_equal(LangId.uk, LangId.new("uk"))
    assert_not_nil(LangId.new("UK").inspect.index("uk"))
    assert_not_nil(LangId.new(0x0022).inspect.index("Ukrainian"))
    assert_equal(0x0422, LangId.uk_UA.to_i)
    assert_equal(LangId.uk_UA, LangId.new("uk-UA"))
    assert_not_nil(LangId.new("UK-UA").inspect.index("uk-UA"))
    assert_not_nil(LangId.new(0x0422).inspect.index("Ukrainian (Ukraine)"))
    assert_equal(0x0020, LangId.ur.to_i)
    assert_equal(LangId.ur, LangId.new("ur"))
    assert_not_nil(LangId.new("UR").inspect.index("ur"))
    assert_not_nil(LangId.new(0x0020).inspect.index("Urdu"))
    assert_equal(0x0420, LangId.ur_PK.to_i)
    assert_equal(LangId.ur_PK, LangId.new("ur-PK"))
    assert_not_nil(LangId.new("UR-PK").inspect.index("ur-PK"))
    assert_not_nil(LangId.new(0x0420).inspect.index("Urdu (Islamic Republic of Pakistan)"))
    assert_equal(0x0043, LangId.uz.to_i)
    assert_equal(LangId.uz, LangId.new("uz"))
    assert_not_nil(LangId.new("UZ").inspect.index("uz"))
    assert_not_nil(LangId.new(0x0043).inspect.index("Uzbek"))
    assert_equal(0x7843, LangId.uz_Cyrl.to_i)
    assert_equal(LangId.uz_Cyrl, LangId.new("uz-Cyrl"))
    assert_not_nil(LangId.new("UZ-CYRL").inspect.index("uz-Cyrl"))
    assert_not_nil(LangId.new(0x7843).inspect.index("Uzbek (Cyrillic)"))
    assert_equal(0x0843, LangId.uz_Cyrl_UZ.to_i)
    assert_equal(LangId.uz_Cyrl_UZ, LangId.new("uz-Cyrl-UZ"))
    assert_not_nil(LangId.new("UZ-CYRL-UZ").inspect.index("uz-Cyrl-UZ"))
    assert_not_nil(LangId.new(0x0843).inspect.index("Uzbek (Cyrillic, Uzbekistan)"))
    assert_equal(0x7c43, LangId.uz_Latn.to_i)
    assert_equal(LangId.uz_Latn, LangId.new("uz-Latn"))
    assert_not_nil(LangId.new("UZ-LATN").inspect.index("uz-Latn"))
    assert_not_nil(LangId.new(0x7c43).inspect.index("Uzbek (Latin)"))
    assert_equal(0x0443, LangId.uz_Latn_UZ.to_i)
    assert_equal(LangId.uz_Latn_UZ, LangId.new("uz-Latn-UZ"))
    assert_not_nil(LangId.new("UZ-LATN-UZ").inspect.index("uz-Latn-UZ"))
    assert_not_nil(LangId.new(0x0443).inspect.index("Uzbek (Latin, Uzbekistan)"))
    assert_equal(0x002a, LangId.vi.to_i)
    assert_equal(LangId.vi, LangId.new("vi"))
    assert_not_nil(LangId.new("VI").inspect.index("vi"))
    assert_not_nil(LangId.new(0x002a).inspect.index("Vietnamese"))
    assert_equal(0x042a, LangId.vi_VN.to_i)
    assert_equal(LangId.vi_VN, LangId.new("vi-VN"))
    assert_not_nil(LangId.new("VI-VN").inspect.index("vi-VN"))
    assert_not_nil(LangId.new(0x042a).inspect.index("Vietnamese (Vietnam)"))
    assert_equal(0x0088, LangId.wo.to_i)
    assert_equal(LangId.wo, LangId.new("wo"))
    assert_not_nil(LangId.new("WO").inspect.index("wo"))
    assert_not_nil(LangId.new(0x0088).inspect.index("Wolof"))
    assert_equal(0x0488, LangId.wo_SN.to_i)
    assert_equal(LangId.wo_SN, LangId.new("wo-SN"))
    assert_not_nil(LangId.new("WO-SN").inspect.index("wo-SN"))
    assert_not_nil(LangId.new(0x0488).inspect.index("Wolof (Senegal)"))
    assert_equal(0x0034, LangId.xh.to_i)
    assert_equal(LangId.xh, LangId.new("xh"))
    assert_not_nil(LangId.new("XH").inspect.index("xh"))
    assert_not_nil(LangId.new(0x0034).inspect.index("isiXhosa"))
    assert_equal(0x0434, LangId.xh_ZA.to_i)
    assert_equal(LangId.xh_ZA, LangId.new("xh-ZA"))
    assert_not_nil(LangId.new("XH-ZA").inspect.index("xh-ZA"))
    assert_not_nil(LangId.new(0x0434).inspect.index("isiXhosa (South Africa)"))
    assert_equal(0x006a, LangId.yo.to_i)
    assert_equal(LangId.yo, LangId.new("yo"))
    assert_not_nil(LangId.new("YO").inspect.index("yo"))
    assert_not_nil(LangId.new(0x006a).inspect.index("Yoruba"))
    assert_equal(0x046a, LangId.yo_NG.to_i)
    assert_equal(LangId.yo_NG, LangId.new("yo-NG"))
    assert_not_nil(LangId.new("YO-NG").inspect.index("yo-NG"))
    assert_not_nil(LangId.new(0x046a).inspect.index("Yoruba (Nigeria)"))
    assert_equal(0x7804, LangId.zh.to_i)
    assert_equal(LangId.zh, LangId.new("zh"))
    assert_not_nil(LangId.new("ZH").inspect.index("zh"))
    assert_not_nil(LangId.new(0x7804).inspect.index("Chinese"))
    assert_equal(0x0804, LangId.zh_CN.to_i)
    assert_equal(LangId.zh_CN, LangId.new("zh-CN"))
    assert_not_nil(LangId.new("ZH-CN").inspect.index("zh-CN"))
    assert_not_nil(LangId.new(0x0804).inspect.index("Chinese (Simplified, PRC)"))
    assert_equal(0x0c04, LangId.zh_HK.to_i)
    assert_equal(LangId.zh_HK, LangId.new("zh-HK"))
    assert_not_nil(LangId.new("ZH-HK").inspect.index("zh-HK"))
    assert_not_nil(LangId.new(0x0c04).inspect.index("Chinese (Traditional, Hong Kong S.A.R.)"))
    assert_equal(0x0004, LangId.zh_Hans.to_i)
    assert_equal(LangId.zh_Hans, LangId.new("zh-Hans"))
    assert_not_nil(LangId.new("ZH-HANS").inspect.index("zh-Hans"))
    assert_not_nil(LangId.new(0x0004).inspect.index("Chinese (Simplified)"))
    assert_equal(0x7c04, LangId.zh_Hant.to_i)
    assert_equal(LangId.zh_Hant, LangId.new("zh-Hant"))
    assert_not_nil(LangId.new("ZH-HANT").inspect.index("zh-Hant"))
    assert_not_nil(LangId.new(0x7c04).inspect.index("Chinese (Traditional)"))
    assert_equal(0x1404, LangId.zh_MO.to_i)
    assert_equal(LangId.zh_MO, LangId.new("zh-MO"))
    assert_not_nil(LangId.new("ZH-MO").inspect.index("zh-MO"))
    assert_not_nil(LangId.new(0x1404).inspect.index("Chinese (Traditional, Macao S.A.R.)"))
    assert_equal(0x1004, LangId.zh_SG.to_i)
    assert_equal(LangId.zh_SG, LangId.new("zh-SG"))
    assert_not_nil(LangId.new("ZH-SG").inspect.index("zh-SG"))
    assert_not_nil(LangId.new(0x1004).inspect.index("Chinese (Simplified, Singapore)"))
    assert_equal(0x0404, LangId.zh_TW.to_i)
    assert_equal(LangId.zh_TW, LangId.new("zh-TW"))
    assert_not_nil(LangId.new("ZH-TW").inspect.index("zh-TW"))
    assert_not_nil(LangId.new(0x0404).inspect.index("Chinese (Traditional, Taiwan)"))
    assert_equal(0x0035, LangId.zu.to_i)
    assert_equal(LangId.zu, LangId.new("zu"))
    assert_not_nil(LangId.new("ZU").inspect.index("zu"))
    assert_not_nil(LangId.new(0x0035).inspect.index("isiZulu"))
    assert_equal(0x0435, LangId.zu_ZA.to_i)
    assert_equal(LangId.zu_ZA, LangId.new("zu-ZA"))
    assert_not_nil(LangId.new("ZU-ZA").inspect.index("zu-ZA"))
    assert_not_nil(LangId.new(0x0435).inspect.index("isiZulu (South Africa)"))
  end

  def test_alias
    assert_equal(0x0004, LangId.new("zh-CHS").to_i)
    assert_equal(0x7c04, LangId.new("zh-CHT").to_i)
  end
  
end
